### PR TITLE
Fix/fix bug in update spec

### LINKED ISSUE #692: [Bug] invalidType not working after invoke updateSpec
English: change invalidType:'zero'  into 'break' not working.
Chinese: 断开方式由zero更新为break不生效.

Image

---
 
```
const spec = {
  "type": "line",
  "xField": [
    "230825165341023"
  ],
  "yField": [
    "10002"
  ],
  "direction": "vertical",
  "seriesField": "20001",
  "data": [
    {
      "id": "data",
      "values": [
        {
          "10001": "数量",
          "10002": "1785",
          "10003": "230825165341017",
          "20001": "数量",
          "230825165341017": "1785",
          "230825165341023": "西北"
        },
        {
          "10001": "销售额-存在空",
          "10002": "815039.5979347229",
          "10003": "230825165341078",
          "20001": "销售额-存在空",
          "230825165341023": "西北",
          "230825165341078": "815039.5979347229"
        },
        {
          "10001": "数量",
          "10002": "9700",
          "10003": "230825165341017",
          "20001": "数量",
          "230825165341017": "9700",
          "230825165341023": "中南"
        },
        {
          "10001": "销售额-存在空",
          "10002": "4137415.0951108932",
          "10003": "230825165341078",
          "20001": "销售额-存在空",
          "230825165341023": "中南",
          "230825165341078": "4137415.0951108932"
        },
        {
          "10001": "数量",
          "10002": "6463",
          "10003": "230825165341017",
          "20001": "数量",
          "230825165341017": "6463",
          "230825165341023": "地区-dongbei"
        },
        {
          "10001": "销售额-存在空",
          "10002": "2681567.4745378494",
          "10003": "230825165341078",
          "20001": "销售额-存在空",
          "230825165341023": "地区-dongbei",
          "230825165341078": "2681567.4745378494"
        },
        {
          "10001": "数量",
          "10002": "3399",
          "10003": "230825165341017",
          "20001": "数量",
          "230825165341017": "3399",
          "230825165341023": "西南"
        },
        {
          "10001": "销售额-存在空",
          "10002": "1303124.5089645386",
          "10003": "230825165341078",
          "20001": "销售额-存在空",
          "230825165341023": "西南",
          "230825165341078": "1303124.5089645386"
        },
        {
          "10001": "数量",
          "10002": "11041",
          "10003": "230825165341017",
          "20001": "数量",
          "230825165341017": "11041",
          "230825165341023": "华东"
        },
        {
          "10001": "销售额-存在空",
          "10002": "4684506.442247391",
          "10003": "230825165341078",
          "20001": "销售额-存在空",
          "230825165341023": "华东",
          "230825165341078": "4684506.442247391"
        },
        {
          "10001": "数量",
          "10002": "5146",
          "10003": "230825165341017",
          "20001": "数量",
          "230825165341017": "5146",
          "230825165341023": "华北"
        },
        {
          "10001": "销售额-存在空",
          "10002": null,
          "10003": "230825165341078",
          "20001": "销售额-存在空",
          "230825165341023": "华北",
          "230825165341078": null
        }
      ],
      "fields": {
        "10001": {
          "alias": "指标名称 "
        },
        "10002": {
          "alias": "指标值 "
        },
        "20001": {
          "alias": "图例项 ",
          "domain": [
            "数量",
            "销售额-存在空"
          ],
          "lockStatisticsByDomain": true
        },
        "230825165341017": {
          "alias": "数量"
        },
        "230825165341023": {
          "alias": "地区",
          "domain": [
            "地区-dongbei",
            "华北",
            "华东",
            "西北",
            "西南",
            "中南"
          ],
          "lockStatisticsByDomain": true,
          "sortIndex": 0
        },
        "230825165341078": {
          "alias": "销售额-存在空"
        }
      }
    }
  ],
  "axes": [
    {
      "type": "band",
      "tick": {
        "visible": false
      },
      "grid": {
        "visible": false,
        "style": {
          "stroke": "#DADCDD",
          "lineWidth": 1,
          "lineDash": [
            4,
            2
          ]
        }
      },
      "orient": "bottom",
      "visible": true,
      "domainLine": {
        "visible": true,
        "style": {
          "lineWidth": 1,
          "stroke": "#989999"
        }
      },
      "title": {
        "visible": false,
        "text": "地区",
        "style": {
          "fontSize": 12,
          "fill": "#363839",
          "fontWeight": "normal"
        }
      },
      "sampling": false,
      "label": {
        "visible": true,
        "style": {
          "fontSize": 12,
          "fill": "#6F6F6F",
          "angle": 0,
          "fontWeight": "normal"
        },
        "autoHide": true,
        "autoHideMethod": "greedy",
        "flush": true
      },
      "hover": true,
      "background": {
        "visible": false,
        "state": {
          "hover": {
            "fillOpacity": 0.08,
            "fill": "#141414"
          }
        }
      },
      "paddingInner": 0.15,
      "paddingOuter": 0.075
    },
    {
      "type": "linear",
      "tick": {
        "visible": false,
        "style": {
          "stroke": "rgba(255, 255, 255, 0)"
        }
      },
      "niceType": "accurateFirst",
      "grid": {
        "visible": true,
        "style": {
          "stroke": "#DADCDD",
          "lineWidth": 1,
          "lineDash": [
            4,
            2
          ]
        }
      },
      "orient": "left",
      "visible": true,
      "domainLine": {
        "visible": true,
        "style": {
          "lineWidth": 1,
          "stroke": "rgba(255, 255, 255, 0)"
        }
      },
      "title": {
        "visible": false,
        "text": "数量",
        "style": {
          "fontSize": 12,
          "fill": "#363839",
          "fontWeight": "normal"
        }
      },
      "sampling": false,
      "label": {
        "visible": true,
        "style": {
          "fontSize": 12,
          "fill": "#6F6F6F",
          "angle": 0,
          "fontWeight": "normal"
        },
        "autoHide": true,
        "autoHideMethod": "greedy"
      },
      "hover": true,
      "background": {
        "visible": true,
        "state": {
          "hover": {
            "fillOpacity": 0.08,
            "fill": "#141414"
          }
        }
      },
      "zero": true,
      "nice": true
    }
  ],
  "color": {
    "field": "20001",
    "type": "ordinal",
    "range": [
      "#2E62F1",
      "#4DC36A"
    ],
    "specified": {},
    "domain": [
      "数量",
      "销售额-存在空"
    ]
  },
  "legends": [
    {
      "type": "discrete",
      "id": "legend",
      "orient": "right",
      "position": "start",
      "layoutType": "normal",
      "visible": true,
      "hover": false,
      "maxCol": 1,
      "title": {
        "textStyle": {
          "fontSize": 12,
          "fill": "#6F6F6F"
        }
      },
      "item": {
        "spaceRow": 0,
        "spaceCol": 0,
        "padding": {
          "top": 4,
          "bottom": 4,
          "left": 4,
          "right": 22
        },
        "background": {
          "style": {
            "fillOpacity": 0.001
          }
        },
        "label": {
          "style": {
            "fontSize": 12,
            "fill": "#6F6F6F"
          }
        },
        "shape": {
          "style": {
            "symbolType": "square"
          }
        }
      },
      "pager": {
        "textStyle": {},
        "handler": {
          "style": {},
          "state": {
            "disable": {}
          }
        }
      },
      "padding": {
        "top": 0,
        "bottom": 0,
        "left": 16,
        "right": 0
      }
    }
  ],
  "label": {
    "visible": false,
    "overlap": {
      "hideOnHit": true,
      "clampForce": true
    },
    "style": {
      "fontSize": 12,
      "fontWeight": "normal",
      "fill": "#363839",
      "stroke": "rgba(255, 255, 255, 0.8)",
      "lineWidth": 2,
      "strokeOpacity": 1
    },
    "position": "outside",
    "smartInvert": false
  },
  "tooltip": {
    "handler": {}
  },
  "background": "rgba(255, 255, 255, 0)",
  "point": {
    "clipByLayout": true,
    "style": {
      "shape": {
        "type": "ordinal",
        "field": "20001",
        "range": [
          "circle"
        ],
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      },
      "size": {
        "type": "ordinal",
        "field": "20001",
        "range": [
          8
        ],
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      },
      "fill": {
        "field": "20001",
        "type": "ordinal",
        "range": [
          "#2E62F1",
          "#4DC36A"
        ],
        "specified": {},
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      },
      "stroke": {
        "field": "20001",
        "type": "ordinal",
        "range": [
          "#2E62F1",
          "#4DC36A"
        ],
        "specified": {},
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      },
      "strokeOpacity": {
        "type": "ordinal",
        "field": "20001",
        "range": [
          1
        ],
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      },
      "fillOpacity": {
        "type": "ordinal",
        "field": "20001",
        "range": [
          1
        ],
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      }
    },
    "state": {
      "hover": {
        "lineWidth": 2,
        "fillOpacity": 1,
        "strokeOpacity": 1,
        "scaleX": 1.5,
        "scaleY": 1.5
      }
    }
  },
  "line": {
    "clipByLayout": true,
    "style": {
      "curveType": {
        "type": "ordinal",
        "field": "20001",
        "range": [
          "linear"
        ],
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      },
      "lineWidth": {
        "type": "ordinal",
        "field": "20001",
        "range": [
          3
        ],
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      },
      "lineDash": {
        "type": "ordinal",
        "field": "20001",
        "range": [
          [
            0,
            0
          ]
        ],
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      }
    }
  },
  "area": {
    "style": {
      "curveType": {
        "type": "ordinal",
        "field": "20001",
        "range": [
          "linear"
        ],
        "domain": [
          "数量",
          "销售额-存在空"
        ]
      }
    }
  },
  "invalidType": "zero",
  "animation": false,
  "hash": "3ba49dbf97510e87f7139975f823ee5a"
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

setTimeout(() => {
  vchart.updateSpec({
    ...spec,
    "invalidType": "break",
    animation:true
  })
}, 3000)
```

### PR DESCRIPTION
**Pull request by xuefei1313**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #692 #696 #592 #576 #574 #451 

### 🐞 Bugserver case id

64eeb1336781a9008fb4d182
64eeb281e4981d7a335659d1
64eeb382e4981d7a335659d7
64eeb5db99663f87baa389aa
64eeb652e4981d7a335659e5
64eeb78d99663f87baa389ab

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

**Review by kkxxkk2019 — APPROVED** [review]

File: packages/vchart/src/chart/base-chart.ts [hunk 1]
```diff
@@ -826,8 +826,8 @@ export class BaseChart extends CompilableBase implements IChart {
     this.transformSpec(spec);
     // spec set & transformSpec
     // diff meta length;
-    const currentKeys = Object.keys(this._spec);
-    const nextKeys = Object.keys(spec);
+    const currentKeys = Object.keys(this._spec).sort();
```
Comment (kkxxkk2019) [inline packages/vchart/src/chart/base-chart.ts:829]: image

这些 issue 里的 spec 录入到 bugserver 吧，有一个 bugs 目录

Comment (xuefei1313) [reply packages/vchart/src/chart/base-chart.ts:829]: ok
