### PR TITLE
Fix/231 bug after updatedata did not call global scale update domain

### LINKED ISSUE #231: [Bug] after updateData ,did not call global-scale update domain
### Version

1.0.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

1. create a chart
2. update new Data with different sort by seriesField

### Current Behavior

ColorScale.domain did not match data order

### Expected Behavior

ColorScale.domain match data order

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xuefei1313**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #231 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/chart/base-chart.ts [hunk 1]
```diff
@@ -608,11 +608,14 @@ export class BaseChart extends CompilableBase implements IChart {
     }
   }
 
-  updateData(id: StringOrNumber, data: unknown, options?: IParserOptions) {
+  updateData(id: StringOrNumber, data: unknown, updateGlobalScale: boolean = true, options?: IParserOptions) {
```
Comment (kkxxkk2019) [inline packages/vchart/src/chart/base-chart.ts:611]: `options` seems no need?

**Review by kkxxkk2019 — APPROVED** [review]
