### PR TITLE
Fix/wordcloud rect

### LINKED ISSUE #2220: [Feature] wordcloud 支持铺满画布
### What problem does this feature solve?

词云支持铺满画布
img_v3_027p_cbfa31f4-d659-457e-b447-a0da9a91343g
现在：
image

```ts
const spec = {
  type: 'wordCloud',
  nameField: 'name',
  valueField: 'value',
  padding:0,
  width:300,
  height:100,
  background:'pink',
  maskShape:'square',
    wordCloudConfig: {
    zoomToFit: {
      shrink: true,
      fontSizeLimitMin: 5
    }
  },
  data: {
    name: 'baseData',
    values: [
      {
        name: '螺蛳粉',
        value: 957
      },
      {
        name: '钵钵鸡',
        value: 942
      },
      {
        name: '板栗',
        value: 842
      },
      {
        name: '胡辣汤',
        value: 828
      },
      {
        name: '关东煮',
        value: 665
      },
      {
        name: '羊肉汤',
        value: 627
      },
      {
        name: '热干面',
        value: 574
      }
    ]
  }
};
```

### What does the proposed API look like?

```js
maskShape: 'rect'
```

### PR DESCRIPTION
**Pull request by skie1997**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #2220 

### 🐞 Bugserver case id
65c0b8dfce3320008eecf6fe

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/series/word-cloud/config.ts [hunk 1]
```diff
@@ -21,5 +21,6 @@ export const SHAPE_TYPE = [
   'star',
   'cardioid',
   'circle',
-  'pentagon'
+  'pentagon',
```
Comment (xiaoluoHe) [inline packages/vchart/src/series/word-cloud/config.ts:24]: 文档补充一下？

**Review by xiaoluoHe — APPROVED** [review]
