### PR TITLE
fix: change mark default stroke color to the series color

### LINKED ISSUE #173: [Feature] support hollow point in line/area chart

### PR DESCRIPTION
**Pull request by xiaoluoHe**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #173 

### 🐞 Bugserver case id
64ae8e3b6b1b9b008a0f91e5

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/series/base/base-series.ts [hunk 1]
```diff
@@ -690,12 +690,10 @@ export abstract class BaseSeries<T extends ISeriesSpec> extends BaseModel implem
...
     this._rawDataStatistics?.reRunAllTransform();
     this.setSeriesField(this._spec.seriesField);
-    // set mark stroke color follow fill
+    // set mark stroke color follow series color
     // only set normal state in the level lower than level Series
     this.getMarks().forEach(m => {
-      if (m.stateStyle.normal?.fill?.style) {
-        m.setAttribute('stroke', m.stateStyle.normal.fill.style, 'normal', AttributeLevel.Chart);
-      }
+      m.setAttribute('stroke', this.getColorAttribute(), 'normal', AttributeLevel.Series);
```
Comment (kkxxkk2019) [inline packages/vchart/src/series/base/base-series.ts:696]: 这个是不是应该判断下是否配置了 lineWidth? 另外 bugserver 挂了很多

**Review by kkxxkk2019 — APPROVED** [review]
