### PR TITLE
fix: flatten sankeyNodeElement, legend data filter of sankey, fix #345

### LINKED ISSUE #345: [Bug] SankeyChart legends not working
### Version

1.1.0

### Link to Minimal Reproduction

https://visactor.bytedance.net/vchart/demo/sankey-chart/hierarchical-sankey

### Steps to Reproduce

```

const spec = {
  type: 'sankey',
  data: [
    {
      name: 'data',
      values: [
        {
          nodes: [
            {
              value: 100,
              name: 'A',
              children: [
                {
                  name: 'top',
                  value: 40,
                  children: [
                    { name: '00', value: 15 },
                    { name: '01', value: 10 },
                    { name: '02', value: 10 }
                  ]
                },
                {
                  name: 'middle',
                  value: 30,
                  children: [
                    { name: '00', value: 10 },
                    { name: '01', value: 10 },
                    { name: '02', value: 10 }
                  ]
                },
                {
                  name: 'bottom',
                  value: 30
                }
              ]
            },
            {
              value: 80,
              name: 'B',
              children: [
                {
                  name: 'top',
                  value: 40,
                  children: [
                    { name: '00', value: 100 },
                    { name: '01', value: 40 }
                  ]
                },
                {
                  name: 'middle',
                  value: 10
                },
                {
                  name: 'bottom',
                  value: 30
                }
              ]
            },
            {
              value: 50,
              name: 'C',
              children: [
                {
                  name: 'top',
                  value: 20
                },
                {
                  name: 'middle',
                  value: 20
                },
                {
                  name: 'bottom',
                  value: 10
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  categoryField: 'name',
  valueField: 'value',

  nodeAlign: 'left',
  nodeGap: 8,
  nodeWidth: 10,
  minNodeHeight: 4,
  nodeKey: datum => datum.name,

  legends: {
    visible: true,
    type: 'discrete'
  },

  label: {
    visible: true,
    state: {
      blur: {
        fill: '#e8e8e8',
        fillOpacity: 0.15
      }
    }
  },

  node: {
    state: {
      hover: {
        fill: 'red'
      },
      blur: {
        fill: '#e8e8e8',
        fillOpacity: 0.15
      }
    }
  },

  link: {
    backgroundStyle: { fill: '#ccc', fillOpacity: 0.2 },
    fillOpacity: 0.8,
    state: {
      hover: {
        stroke: '#000000'
      },
      blur: {
        fill: '#e8e8e8'
      }
    }
  },

  emphasis: {
    enable: true,
    effect: 'adjacency'
  }
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// 只为了方便控制台调试用，不要拷贝
window['vchart'] = vchart;

```

### Current Behavior

image

### Expected Behavior

legends work well

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by pairone**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #345 

### 🐞 Bugserver case id
64f03a8c4fd6cbae9ab239b9

### 💡 Background and solution

https://github.com/VisActor/VChart/assets/40026218/99e6d968-48ac-48e2-87f0-a44a71b5b25b

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

**Comment by kkxxkk2019** [comment]
image

图例的颜色映射不对，另外需要检查下图例的筛选功能是否正确，再补充下 bugserver case

File: packages/vchart/src/series/sankey/sankey.ts [hunk 1]
```diff
@@ -236,7 +255,12 @@ export class SankeySeries extends CartesianSeries<any> {
         y: (datum: Datum) => datum.y0,
         y1: (datum: Datum) => datum.y1,
         fill: (datum: Datum) => {
-          return this._spec.node?.style?.fill ?? this.getNodeOrdinalColorScale(datum.key);
+          const nodeName = datum.key
```
Comment (kkxxkk2019) [inline packages/vchart/src/series/sankey/sankey.ts:258]: 这个可以直接 datum.key ?? datum[this._spec.categoryField] ?? ''

**Comment by kkxxkk2019** [comment]
冲突解决下，然后吧 bugserver case id 填一下

**Review by kkxxkk2019 — APPROVED** [review]
