### PR TITLE
Fix/issue 769: Legend does not update after updateData

### LINKED ISSUE #769: [Bug] When updateData, legend does not update
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

```ts
  const spec = {
    type: 'pie',
    data: [
      {
        id: 'pieData',
        values: pieData
      }
    ],
    outerRadius: 0.8,
    innerRadius: 0.5,
    padAngle: 0.6,
    valueField: 'value',
    categoryField: 'type',
    // color: {
    //   id: 'color',
    //   type: 'linear',
    //   range: ['#1664FF', '#B2CFFF', '#1AC6FF', '#94EFFF'],
    //   domain: [
    //     {
    //       dataId: 'pieData',
    //       fields: ['value']
    //     }
    //   ]
    // },
    pie: {
      style: {
        cornerRadius: 10
        // fill: {
        //   scale: 'color',
        //   field: 'value'
        // }
      }
    },
    legends: {
      visible: true,
      orient: 'left'
      // data: (data, scale) => {
      //   return data.map(datum => {
      //     const pickDatum = pieData.find(pieDatum => pieDatum.type === datum.label);

      //     datum.shape.fill = scale.scale(pickDatum?.value);
      //     return datum;
      //   });
      // }
    },
    label: {
      visible: true
    }
  };

  const vchart = new VChart(spec, { dom: CONTAINER_ID });
  vchart.renderAsync();
````

Then call

```ts
vchart.updateData('pieData', [
  {type: "AAAA", value: 30},
{type: "BBBB", value: 10}
```

### Current Behavior

legend does not change

image

### Expected Behavior

should change

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by kkxxkk2019**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #769 

### 🐞 Bugserver case id
64f5a7bb2a78e9f552b7428b

| Before | After |
|--------|--------|
| image | image | 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/legend/base-legend.ts [hunk 1]
```diff
@@ -256,6 +256,26 @@ export abstract class BaseLegend<T extends ILegendCommonSpec> extends BaseCompon
     return result;
   }
 
+  onDataUpdate(): void {
+    this._legendData?.getDataView().reRunAllTransform();
+    // 更新当前选中数据
+    this._initSelectedData();
```
Comment (xuefei1313) [inline packages/vchart/src/component/legend/base-legend.ts:262]: 已经有监听数据事件，会自动执行initSelectedData();

File: packages/vchart/src/component/legend/base-legend.ts [hunk 2]
```diff
@@ -256,6 +256,26 @@ export abstract class BaseLegend<T extends ILegendCommonSpec> extends BaseCompon
...
+      if (!isEqual(attrs, this._cacheAttrs)) {
+        this._legendComponent.setAttributes(
+          mergeSpec({}, attrs, {
+            defaultSelected: this._selectedData // 图表 resize 之后应该保留上次筛选的结果
+          })
+        );
+      }
+    }
+    // 更新数据流
+    this.effect.onSelectedDataChange?.();
```
Comment (xuefei1313) [inline packages/vchart/src/component/legend/base-legend.ts:275]: 要不要考虑增加一个判定，比如selectedData没有变化就不执行effect和发消息

**Review by xuefei1313 — DISMISSED** [review]

File: packages/vchart/src/component/legend/base-legend.ts (hunk 1 above)
Comment (kkxxkk2019) [reply packages/vchart/src/component/legend/base-legend.ts:262]: 是因为监听了 change 事件吗

image

**Review by xuefei1313 — APPROVED** [review]
