### PR TITLE
Fix/daily1019

### LINKED ISSUE #1122: [Bug] Gauge Chart Label Obscured by Arc Mark.
Image

### PR DESCRIPTION
**Pull request by zamhown**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #1122, #1123

### 🐞 Bugserver case id
64eeb382e4981d7a335659d7

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/chart/polar/progress-like.ts [hunk 1]
```diff
@@ -72,5 +75,13 @@ export class ProgressLikeChart extends PolarChart {
     if (isNil(axesPtr.angle.max)) {
       axesPtr.angle.max = domain.max;
     }
+    if (angleAxisAppendSpec) {
+      const newSpec = mergeSpec({}, angleAxisAppendSpec, axesPtr.angle);
+      Object.assign(axesPtr.angle, newSpec);
```
Comment (kkxxkk2019) [inline packages/vchart/src/chart/polar/progress-like.ts:80]: 为啥不直接  axesPtr.angle = mergeSpec({}, angleAxisAppendSpec, axesPtr.angle);

Comment (zamhown) [reply packages/vchart/src/chart/polar/progress-like.ts:80]: 对 axesPtr 的修改不会影响 spec 的，但是 Object.assign 可以原地修改 axesPtr.angle，axesPtr.angle 是来自 spec 的一个对象

**Review by kkxxkk2019 — APPROVED** [review]
