### PR TITLE
Fix/component spec

### LINKED ISSUE #93: [Type Definition] component spec upgrade

### PR DESCRIPTION
**Pull request by skie1997**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #93 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/marker/interface.ts [hunk 1]
```diff
@@ -1,13 +1,7 @@
-import type { IPadding, IPointLike } from '@visactor/vutils';
-import type { SymbolType } from '@visactor/vrender';
+import type { IPadding, IPointLike } from '@dp/vis-util';
```
Comment (kkxxkk2019) [inline packages/vchart/src/component/marker/interface.ts:1]: Oops, not '@dp/vis-util', is @visactor/vutils

File: packages/vchart/src/component/marker/interface.ts [hunk 2]
```diff
@@ -1,13 +1,7 @@
...
+import type { SymbolType } from '@dp/canopus';
```
Comment (kkxxkk2019) [inline packages/vchart/src/component/marker/interface.ts:2]: same problem

**Review by kkxxkk2019 — APPROVED** [review]
