### PR TITLE
Fix/wordcloud update data

### LINKED ISSUE #2605: [Bug] wordCloud chart call updateDataSync chart layout error
### Version

develop

### Link to Minimal Reproduction

1

### Steps to Reproduce

const spec = {
    nameField: "Segment",
    padding: 0,
    seriesField: "Segment",
    sortDataByAxis: true,
    type: "wordCloud",
    valueField: "Quantity",
      data: {
        id: 'baseData',
      }
  };
const vchart = new VChart(spec, { dom: CONTAINER_ID,mode: 'desktop-browser',
      canvasControled: false, animation: false,
      interactive: true,
      autoFit: false });
vchart.renderSync();
 vchart.updateDataSync('baseData',[
    {
        "Segment-Indicator": "Consumer-Quantity",
        "Region": "Central",
        "Category": "Furniture",
        "Quantity": "16",
        "Sub-Category": "Chairs",
        "Order Year": "2015",
        "Segment": "Consumer",
        "Ship Mode": "First Class"
    },
    {
        "Segment-Indicator": "Consumer-Quantity",
        "Region": "Central",
        "Category": "Furniture",
        "Quantity": "4",
        "Sub-Category": "Tables",
        "Order Year": "2015",
        "Segment": "Consumer",
        "Ship Mode": "First Class"
    },
    {
        "Segment-Indicator": "Corporate-Quantity",
        "Region": "Central",
        "Category": "Furniture",
        "Quantity": "2",
        "Sub-Category": "Bookcases",
        "Order Year": "2015",
        "Segment": "Corporate",
        "Ship Mode": "First Class"
    },
    {
        "Segment-Indicator": "Consumer-Quantity",
        "Region": "Central",
        "Category": "Furniture",
        "Quantity": "16",
        "Sub-Category": "Furnishings",
        "Order Year": "2015",
        "Segment": "Consumer",
        "Ship Mode": "First Class"
    },
    {
        "Segment-Indicator": "Home Office-Quantity",
        "Region": "Central",
        "Category": "Furniture",
        "Quantity": "1",
        "Sub-Category": "Tables",
        "Order Year": "2015",
        "Segment": "Home Office",
        "Ship Mode": "First Class"
    },
    {
        "Segment-Indicator": "Home Office-Quantity",
        "Region": "Central",
        "Category": "Furniture",
        "Quantity": "2",
        "Sub-Category": "Furnishings",
        "Order Year": "2015",
        "Segment": "Home Office",
        "Ship Mode": "First Class"
    },
    {
        "Segment-Indicator": "Consumer-Quantity",
        "Region": "Central",
        "Category": "Furniture",
        "Quantity": "11",
        "Sub-Category": "Bookcases",
        "Order Year": "2015",
        "Segment": "Consumer",
        "Ship Mode": "First Class"
    }
]);
// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

### Current Behavior

img_v3_02ac_50572dfc-d17d-4863-ad35-93c16ca87c8g

### Expected Behavior

render right

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by skie1997**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related PR link
close #2605 

### 🐞 Bugserver case id
662e11f5b19f5100ced6a605
662e1277b19f5100ced6a606

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

**Review by fangsmile — APPROVED** [review]

File: packages/vchart/src/compile/data/compilable-data.ts [hunk 1]
```diff
@@ -69,7 +69,7 @@ export class CompilableData extends GrammarItem implements ICompilableData {
     }
 
     const id = this.getProductId();
-    this._product = view.data(data).id(id);
+    this._product = view?.data?.(data).id(id);
```
Comment (xile611) [inline packages/vchart/src/compile/data/compilable-data.ts:72]: `view?.data?.(data)?.id(id)`
id 前面不需要加上`?.` 吗

**Review by xile611 — APPROVED** [review]
