### PR TITLE
Fix/one by one delay

### LINKED ISSUE #1602: [Bug] animation oneByOne not effect in horizontal bar chart
### Version

1.6.3

### Link to Minimal Reproduction

vscreen

### Steps to Reproduce

```ts
const spec = {
    "type": "bar",
    "xField": [
        "10002"
    ],
    "yField": [
        "OCxMNY4j86cy",
        "10001"
    ],
    "direction": "horizontal",
    "sortDataByAxis": true,
    "seriesField": "30001",
    "padding": {
        "left": 6,
        "right": 6,
        "top": 6,
        "bottom": 6
    },
    "labelLayout": "region",
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "10001": "Profit",
                    "10002": 20,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2023",
                    "OCxMNY4j86cy": "Labels",
                    "XU0wVG43cGL7": 20,
                    "vGTOlXqnCrc3": "2023"
                },
                {
                    "10001": "Profit",
                    "10002": 44,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2022",
                    "OCxMNY4j86cy": "Labels",
                    "XU0wVG43cGL7": 44,
                    "vGTOlXqnCrc3": "2022"
                },
                {
                    "10001": "Profit",
                    "10002": 15,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2023",
                    "OCxMNY4j86cy": "Tables",
                    "XU0wVG43cGL7": 15,
                    "vGTOlXqnCrc3": "2023"
                },
                {
                    "10001": "Profit",
                    "10002": 20,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2022",
                    "OCxMNY4j86cy": "Tables",
                    "XU0wVG43cGL7": 20,
                    "vGTOlXqnCrc3": "2022"
                },
                {
                    "10001": "Profit",
                    "10002": 50,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2023",
                    "OCxMNY4j86cy": "Storage",
                    "XU0wVG43cGL7": 50,
                    "vGTOlXqnCrc3": "2023"
                },
                {
                    "10001": "Profit",
                    "10002": 65,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2022",
                    "OCxMNY4j86cy": "Storage",
                    "XU0wVG43cGL7": 65,
                    "vGTOlXqnCrc3": "2022"
                },
                {
                    "10001": "Profit",
                    "10002": 15,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2023",
                    "OCxMNY4j86cy": "Furn",
                    "XU0wVG43cGL7": 15,
                    "vGTOlXqnCrc3": "2023"
                },
                {
                    "10001": "Profit",
                    "10002": 40,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2022",
                    "OCxMNY4j86cy": "Furn",
                    "XU0wVG43cGL7": 40,
                    "vGTOlXqnCrc3": "2022"
                },
                {
                    "10001": "Profit",
                    "10002": 57,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2023",
                    "OCxMNY4j86cy": "Art",
                    "XU0wVG43cGL7": 57,
                    "vGTOlXqnCrc3": "2023"
                },
                {
                    "10001": "Profit",
                    "10002": 35,
                    "10003": "XU0wVG43cGL7",
                    "30001": "2022",
                    "OCxMNY4j86cy": "Art",
                    "XU0wVG43cGL7": 35,
                    "vGTOlXqnCrc3": "2022"
                }
            ],
            "fields": {
                "10001": {
                    "alias": "指标名称"
                },
                "10002": {
                    "alias": "指标值"
                },
                "30001": {
                    "alias": "图例项",
                    "domain": [
                        "2023",
                        "2022"
                    ],
                    "sortIndex": 0,
                    "lockStatisticsByDomain": true
                },
                "OCxMNY4j86cy": {
                    "alias": "Product",
                    "domain": [
                        "Labels",
                        "Labels",
                        "Tables",
                        "Tables",
                        "Storage",
                        "Storage",
                        "Furn",
                        "Furn",
                        "Art",
                        "Art"
                    ],
                    "sortIndex": 0,
                    "lockStatisticsByDomain": true
                },
                "vGTOlXqnCrc3": {
                    "alias": "Year"
                },
                "XU0wVG43cGL7": {
                    "alias": "Profit"
                }
            }
        }
    ],
    "stackInverse": false,
    "axes": [
        {
            "type": "band",
            "tick": {
                "visible": false
            },
            "grid": {
                "visible": false,
                "style": {
                    "zIndex": 150,
                    "stroke": "#FFFFFF",
                    "lineWidth": 1,
                    "lineDash": []
                }
            },
            "orient": "left",
            "visible": true,
            "domainLine": {
                "visible": false,
                "style": {
                    "lineWidth": 1,
                    "stroke": "#d5d7e2"
                }
            },
            "title": {
                "visible": false,
                "space": 5,
                "text": "",
                "style": {
                    "fontSize": 12,
                    "fill": "rgba(255,255,255,0.5)",
                    "fontFamily": "D-DIN",
                    "fontWeight": "normal"
                }
            },
            "sampling": false,
            "zIndex": 200,
            "label": {
                "visible": true,
                "space": 8,
                "style": {
                    "fontSize": 12,
                    "fill": "rgba(255,255,255,0.65)",
                    "angle": 0,
                    "fontFamily": "D-DIN",
                    "fontWeight": "normal",
                    "direction": "horizontal"
                },
                "autoHide": true,
                "autoHideMethod": "greedy",
                "flush": true
            },
            "hover": true,
            "background": {
                "visible": true,
                "state": {
                    "hover": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    },
                    "hover_reverse": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    }
                }
            },
            "paddingInner": [
                0.15,
                0.1
            ],
            "paddingOuter": [
                0.075,
                0.1
            ],
            "ticks": false,
            "rangeType": "rough"
        },
        {
            "type": "linear",
            "tick": {
                "visible": false,
                "tickMode": "d3",
                "style": {
                    "stroke": "#d5d7e2"
                }
            },
            "niceType": "accurateFirst",
            "zIndex": 200,
            "grid": {
                "visible": true,
                "style": {
                    "zIndex": 150,
                    "stroke": "rgba(255,255,255,0.15)",
                    "lineWidth": 1,
                    "lineDash": []
                }
            },
            "orient": "bottom",
            "visible": true,
            "domainLine": {
                "visible": false,
                "style": {
                    "lineWidth": 1,
                    "stroke": "#d5d7e2"
                }
            },
            "title": {
                "visible": false,
                "text": "",
                "space": 8,
                "style": {
                    "fontSize": 12,
                    "fill": "rgba(255,255,255,0.5)",
                    "fontFamily": "D-DIN",
                    "fontWeight": "normal"
                }
            },
            "sampling": false,
            "label": {
                "visible": true,
                "space": 4,
                "flush": true,
                "padding": 0,
                "style": {
                    "fontSize": 12,
                    "maxLineWidth": 174,
                    "fill": "rgba(255,255,255,0.65)",
                    "angle": 0,
                    "fontFamily": "D-DIN",
                    "fontWeight": "normal",
                    "dy": -1,
                    "direction": "horizontal"
                },
                "autoHide": true,
                "autoHideMethod": "greedy",
                "rotateAngle": [
                    null
                ],
                "labelOverlap": "custom",
                "tighten": false
            },
            "hover": true,
            "background": {
                "visible": true,
                "state": {
                    "hover": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    },
                    "hover_reverse": {
                        "fillOpacity": 0.08,
                        "fill": "#141414"
                    }
                }
            },
            "zero": true,
            "nice": true,
            "rangeType": "rough"
        }
    ],
    "color": {
        "field": "30001",
        "type": "ordinal",
        "range": [
            "rgb(0,110,255)",
            "rgb(0,229,229)"
        ],
        "specified": {}
    },
    "colorGradient": {
        "type": "linear",
        "x0": {
            "field": "30001",
            "type": "ordinal",
            "range": [
                0,
                0
            ]
        },
        "y0": {
            "field": "30001",
            "type": "ordinal",
            "range": [
                1,
                1
            ]
        },
        "x1": {
            "field": "30001",
            "type": "ordinal",
            "range": [
                1,
                1
            ]
        },
        "y1": {
            "field": "30001",
            "type": "ordinal",
            "range": [
                1,
                1
            ]
        },
        "stops": [
            {
                "offset": 0,
                "color": {
                    "field": "30001",
                    "type": "ordinal",
                    "range": [
                        "rgba(0,110,255,0.2)",
                        "rgba(0,229,229,0.2)"
                    ]
                }
            },
            {
                "offset": 1,
                "color": {
                    "field": "30001",
                    "type": "ordinal",
                    "range": [
                        "rgb(0,110,255)",
                        "rgb(0,229,229)"
                    ]
                }
            }
        ]
    },
    "legends": [
        {
            "type": "discrete",
            "id": "legend-discrete",
            "orient": "top",
            "position": "end",
            "layoutType": "normal",
            "visible": true,
            "maxRow": 1,
            "title": {
                "textStyle": {
                    "fontSize": 12,
                    "fill": "rgba(255,255,255,0.45)"
                }
            },
            "layoutLevel": 50,
            "item": {
                "shape": {},
                "label": {
                    "style": {
                        "color": "rgba(255,255,255,0.45)",
                        "fontSize": 12,
                        "fontFamily": "D-DIN",
                        "fontWeight": "normal",
                        "fill": "rgba(255,255,255,0.45)"
                    }
                },
                "value": {
                    "style": {
                        "color": "rgba(255,255,255,0.45)",
                        "fontSize": 12,
                        "fontFamily": "D-DIN",
                        "fontWeight": "normal",
                        "fill": "rgba(255,255,255,0.45)"
                    }
                }
            },
            "pager": {
                "layout": "horizontal",
                "padding": 0,
                "textStyle": {},
                "space": 0,
                "handler": {
                    "preShape": "triangleLeft",
                    "nextShape": "triangleRight",
                    "style": {},
                    "state": {
                        "disable": {}
                    }
                }
            },
            "padding": {
                "top": 0,
                "bottom": 16,
                "left": 0,
                "right": 0
            }
        }
    ],
    "label": {
        "visible": false,
        "offset": 0,
        "overlap": {
            "hideOnHit": true,
            "avoidBaseMark": false,
            "strategy": [
                {
                    "type": "position",
                    "position": []
                },
                {
                    "type": "moveY",
                    "offset": [
                        -5,
                        -4,
                        -3,
                        -2,
                        -1,
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                },
                {
                    "type": "moveX",
                    "offset": [
                        -5,
                        -4,
                        -3,
                        -2,
                        -1,
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                }
            ],
            "clampForce": true
        },
        "style": {
            "fontSize": 12,
            "fontFamily": "D-DIN",
            "fontWeight": "normal",
            "zIndex": 400,
            "fill": "rgba(255,255,255,1)",
            "strokeOpacity": 0
        },
        "position": "outside",
        "smartInvert": false
    },
    "tooltip": {
        "style": {
            "panel": {
                "padding": {
                    "top": 5,
                    "bottom": 10,
                    "left": 10,
                    "right": 10
                },
                "backgroundColor": "rgba(47, 59, 82, 0.9)",
                "border": {
                    "color": "#fff",
                    "width": 0,
                    "radius": 4
                },
                "shadow": {
                    "x": 0,
                    "y": 4,
                    "blur": 12,
                    "spread": 0,
                    "color": "rgba(0, 0, 0, 0.2)"
                }
            },
            "titleLabel": {
                "fontSize": 14,
                "fontColor": "#fff",
                "align": "left",
                "lineHeight": 18
            },
            "keyLabel": {
                "fontSize": 12,
                "fontColor": "#fff",
                "align": "left",
                "lineHeight": 18
            },
            "valueLabel": {
                "fontSize": 12,
                "fontColor": "#fff",
                "align": "right",
                "lineHeight": 18
            },
            "shape": {
                "size": 10,
                "spacing": 10
            },
            "spaceRow": 10
        }
    },
    "hover": {
        "enable": true
    },
    "select": {
        "enable": true
    },
    "bar": {
        "state": {
            "hover": {
                "cursor": "pointer",
                "fillOpacity": 0.8,
                "stroke": "#58595B",
                "lineWidth": 1,
                "zIndex": 500
            },
            "selected": {
                "cursor": "pointer",
                "fillOpacity": 1,
                "stroke": "#58595B",
                "lineWidth": 1
            },
            "selected_reverse": {
                "fillOpacity": 0.3,
                "strokeWidth": 0.3
            }
        },
        "style": {
            "cornerRadius": 0
        }
    },
    "region": [
        {
            "clip": true
        }
    ],
    "background": "rgba(0, 0, 0, 1)",
    "animation": true,
    "brush": {
        "inBrush": {
            "fillOpacity": 1,
            "stroke": "#58595B",
            "lineWidth": 1,
            "colorAlpha": 1
        },
        "outOfBrush": {
            "colorAlpha": 0.2,
            "fillOpacity": 0.3,
            "strokeWidth": 0.3
        }
    },
    "barSpec": {
        "fillOpacity": 0.4
    },
    "labels": {
        "fontWeight": "normal",
        "fontFamily": "D-DIN"
    },
    "axesPadding": true,
    "crosshair": {
        "xField": {
            "line": {
                "style": {
                    "fill": "rgba(47, 59, 82, 0.9)"
                }
            }
        },
        "yField": {
            "line": {
                "style": {
                    "fill": "rgba(47, 59, 82, 0.9)"
                }
            }
        }
    },
    "plotLayout": {
        "clip": false
    },
    "barPadding": 0.6,
    "paddingInGroup": 0.35,
    "barWidth": "60%",
    "animationAppear": {
        "bar": {
            "type": "fadeIn",
            "oneByOne": true,
            "duration": 1000,
            "delay": 4000,
            "loop": true
        }
    },
    "animationUpdate": {
        "bar": {
            "type": "fadeIn",
            "oneByOne": true,
            "duration": 1000,
            "delay": 4000,
            "loop": false
        }
    },
    "animationEnter": {
        "bar": {
            "type": "fadeIn",
            "oneByOne": true,
            "duration": 1000,
            "delay": 4000,
            "loop": false
        }
    }
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

### Current Behavior

20231124114142_rec_

### Expected Behavior

20231124114222_rec_

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by purpose233**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

Fix #1602 #1596

### 💡 Background and solution

Fix delay & delayAfter time for loop oneByOne animations

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/series/waterfall/waterfall.ts [hunk 1]
```diff
@@ -149,17 +149,23 @@ export class WaterfallSeries<T extends IWaterfallSeriesSpec = IWaterfallSeriesSp
 
     // 分组数据的dataIndex应该与x轴顺序一致，而非data[DEFAULT_DATA_INDEX]顺序
     const dataIndex = (datum: any) => {
-      const xValue = datum?.[this._fieldX[0]];
-      const xIndex = this.getViewDataStatistics()?.latestData?.[this._fieldX[0]]?.values.indexOf(xValue);
+      const indexField = this.direction === 'horizontal' ? this._fieldY[0] : this._fieldX[0];
```
Comment (kkxxkk2019) [inline packages/vchart/src/series/waterfall/waterfall.ts:152]: 这两个方法看上去都是重复的，是不是应该抽一下

Comment (purpose233) [reply packages/vchart/src/series/waterfall/waterfall.ts]: Fixed.

**Review by kkxxkk2019 — APPROVED** [review]
