### PR TITLE
fix: fix issue of animation state

### LINKED ISSUE #4397: [Bug] 图形自定义状态设置层级无效
### Version

2.0.13

### Link to Minimal Reproduction

null

### Steps to Reproduce

1. 设置自定义状态层级高于内置 hover
2. 自定义状态和 hover 同时修改同一个属性 比如fill
3. 交互后，自定义状态的fill被hover覆盖

### Current Behavior

交互后，自定义状态的fill被hover覆盖

### Expected Behavior

交互后，自定义状态的fill优先级更高，不被hover覆盖

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xuefei1313**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #4397 #4383

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/mark/base/base-mark.ts [hunk 1]
```diff
@@ -1551,9 +1552,15 @@ export class BaseMark<T extends ICommonSpec> extends GrammarItem implements IMar
 
   protected _runEncoder(graphics: IMarkGraphic[], noGroupEncode?: boolean) {
     const attrsByGroup = noGroupEncode ? null : this._runGroupEncoder(this._encoderOfState?.group);
-
     graphics.forEach((g, index) => {
-      const attrs = this._runEncoderOfGraphic(this._encoderOfState?.update, g);
+      let attrs = this._runEncoderOfGraphic(this._encoderOfState?.update, g);
+      g.currentStates?.forEach((_state: string) => {
+        const stateAttr = this._runGroupEncoder(this._encoderOfState?.[_state])?.[g.context.groupKey];
```
Comment (xile611) [inline packages/vchart/src/mark/base/base-mark.ts]: 这个是解决什么问题来着，有点忘了？要不要加一下注释？
