### PR TITLE
Fix/marker aggr bug

### LINKED ISSUE #1380: [Bug] when markline autorange is set, setLegendSelectedData will cause render error
### Version

1.5.3

### Link to Minimal Reproduction

null

### Steps to Reproduce

code demo: https://codesandbox.io/p/sandbox/vchart-1-5-3-5z6gxd?file=%2Fsrc%2FApp.tsx%3A1%2C1

### Current Behavior

render error.

### Expected Behavior

corrent chart result.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by skie1997**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related PR link

close #1380
### 🐞 Bugserver case id
6543d725f5cd21e90b0fc831

### 💡 Background and solution
当数据被筛选后为[]时，markline计算data aggregation返回`-Infinity`或`Infinity`导致轴被意外拓展。
解决前:
20231103011209_rec_

解决后:
20231103011128_rec_

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/util/math.ts [hunk 1]
```diff
@@ -96,10 +96,18 @@ export function outOfBounds(bounds: IBoundsLike, x: number, y: number) {
   return bounds.x1 > x || bounds.x2 < x || bounds.y1 > y || bounds.y2 < y;
 }
 export function min(data: any[], field?: string): number {
-  return minInArray(data.map(d => +d[field]).filter(d => isValidNumber(d)));
+  const dataArray = data.map(d => +d[field]).filter(d => isValidNumber(d));
```
Comment (kkxxkk2019) [inline packages/vchart/src/util/math.ts:99]: 可以直接走一遍循环，没必要走两遍

File: packages/vchart/src/util/math.ts [hunk 2]
```diff
@@ -96,10 +96,18 @@ export function outOfBounds(bounds: IBoundsLike, x: number, y: number) {
...
+  }
+  return minInArray(dataArray);
 }
 
 export function max(data: any[], field?: string): number {
+  const dataArray = data.map(d => +d[field]).filter(d => isValidNumber(d));
+  if (dataArray.length === 0) {
+    return null;
+  }
   return maxInArray(data.map(d => +d[field]).filter(d => isValidNumber(d)));
```
Comment (kkxxkk2019) [inline packages/vchart/src/util/math.ts:111]: 上面已经过滤过了，直接取上面的变量值

**Review by kkxxkk2019 — APPROVED** [review]

**Review by kkxxkk2019 — APPROVED** [review]
