### PR TITLE
Fix: event prevent level

### LINKED ISSUE #3728: [Bug] 拖拽事件无法正确释放
### Version

latest

### Link to Minimal Reproduction

null

### Steps to Reproduce

[spec(6).txt](https://github.com/user-attachments/files/18781498/spec.6.txt)

### Current Behavior

Image

### Expected Behavior

拖拽画布时，鼠标能正确释放

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xiaoluoHe**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
 closes #3728

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

**Review by skie1997 — DISMISSED** [review]

File: packages/vchart/src/interaction/zoom/zoomable.ts [hunk 1]
```diff
@@ -538,7 +538,14 @@ export class Zoomable implements IZoomable {
         return;
       }
       this._clickEnable = false;
-      end.forEach(endEventType => this._eventObj.prevent(endEventType, this._handleDragMouseUp as any));
+      end.forEach(endEventType => {
+        if (endEventType === 'pointerup') {
```
Comment (xile611) [inline packages/vchart/src/interaction/zoom/zoomable.ts:542]: 这是写错层级了吗

**Review by xile611 — APPROVED** [review]
