### PR TITLE
Fix/issue 337

### LINKED ISSUE #337: [Bug] common chart not support single legend.allowAllCanceled
```js
const spec = {
  "type": "common",
  "color": [
    "#4E83FD",
    "#50CEFB",
    "#935AF6",
    "#FAD355",
    "#F76964",
    "#FFA53D",
    "#F14BA9",
    "#14E1C6",
    "#DB66DB",
    "#C3DD40",
    "#616AE5",
    "#62D256"
  ],
  "data": [
    {
      "id": "comboBarData",
      "values": [
        {
          "dataSeries": "bar",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "ttt",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "ttt",
          "98ae0a68-7207-4ed9-87b4-59181d8f7bf0": 1000,
          "e7f83841-4f05-46dd-838f-eab66307c5a7": 1000
        },
        {
          "dataSeries": "bar",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张一",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张一",
          "98ae0a68-7207-4ed9-87b4-59181d8f7bf0": 3024,
          "e7f83841-4f05-46dd-838f-eab66307c5a7": 3428
        },
        {
          "dataSeries": "bar",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张三",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张三",
          "98ae0a68-7207-4ed9-87b4-59181d8f7bf0": 20318,
          "e7f83841-4f05-46dd-838f-eab66307c5a7": 17685
        },
        {
          "dataSeries": "bar",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张二",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张二",
          "98ae0a68-7207-4ed9-87b4-59181d8f7bf0": 13079,
          "e7f83841-4f05-46dd-838f-eab66307c5a7": 9977
        },
        {
          "dataSeries": "bar",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张五",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张五",
          "98ae0a68-7207-4ed9-87b4-59181d8f7bf0": 5387,
          "e7f83841-4f05-46dd-838f-eab66307c5a7": 6932
        },
        {
          "dataSeries": "bar",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张四",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张四",
          "98ae0a68-7207-4ed9-87b4-59181d8f7bf0": 12892,
          "e7f83841-4f05-46dd-838f-eab66307c5a7": 15534
        }
      ],
      "transforms": [
        {
          "type": "fold",
          "options": {
            "key": "measure",
            "value": "value",
            "fields": [
              "98ae0a68-7207-4ed9-87b4-59181d8f7bf0",
              "e7f83841-4f05-46dd-838f-eab66307c5a7"
            ]
          }
        }
      ]
    },
    {
      "id": "comboLineData",
      "values": [
        {
          "dataSeries": "line",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "ttt",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "ttt",
          "268a3dc9-bb14-45d7-aaf4-b8893a68784b": 1000,
          "__VCHART_DEFAULT_DATA_SERIES_FIELD": "line",
          "__VCHART_DEFAULT_DATA_INDEX": 0,
          "__VCHART_DEFAULT_DATA_KEY": "ttt_0",
          "VGRAMMAR_DATA_ID_KEY_113": 0
        },
        {
          "dataSeries": "line",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张一",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张一",
          "268a3dc9-bb14-45d7-aaf4-b8893a68784b": 3299,
          "__VCHART_DEFAULT_DATA_SERIES_FIELD": "line",
          "__VCHART_DEFAULT_DATA_INDEX": 1,
          "__VCHART_DEFAULT_DATA_KEY": "张一_0",
          "VGRAMMAR_DATA_ID_KEY_113": 1
        },
        {
          "dataSeries": "line",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张三",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张三",
          "268a3dc9-bb14-45d7-aaf4-b8893a68784b": 16604,
          "__VCHART_DEFAULT_DATA_SERIES_FIELD": "line",
          "__VCHART_DEFAULT_DATA_INDEX": 2,
          "__VCHART_DEFAULT_DATA_KEY": "张三_0",
          "VGRAMMAR_DATA_ID_KEY_113": 2
        },
        {
          "dataSeries": "line",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张二",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张二",
          "268a3dc9-bb14-45d7-aaf4-b8893a68784b": 9077,
          "__VCHART_DEFAULT_DATA_SERIES_FIELD": "line",
          "__VCHART_DEFAULT_DATA_INDEX": 3,
          "__VCHART_DEFAULT_DATA_KEY": "张二_0",
          "VGRAMMAR_DATA_ID_KEY_113": 3
        },
        {
          "dataSeries": "line",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张五",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张五",
          "268a3dc9-bb14-45d7-aaf4-b8893a68784b": 4132,
          "__VCHART_DEFAULT_DATA_SERIES_FIELD": "line",
          "__VCHART_DEFAULT_DATA_INDEX": 4,
          "__VCHART_DEFAULT_DATA_KEY": "张五_0",
          "VGRAMMAR_DATA_ID_KEY_113": 4
        },
        {
          "dataSeries": "line",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9": "张四",
          "73b0e523-881e-41a6-bb8e-4f09d67592b9-originData": "张四",
          "268a3dc9-bb14-45d7-aaf4-b8893a68784b": 14028,
          "__VCHART_DEFAULT_DATA_SERIES_FIELD": "line",
          "__VCHART_DEFAULT_DATA_INDEX": 5,
          "__VCHART_DEFAULT_DATA_KEY": "张四_0",
          "VGRAMMAR_DATA_ID_KEY_113": 5
        }
      ]
    }
  ],
  "series": [
    {
      "type": "bar",
      "id": "bar",
      "dataIndex": 0,
      "animation": false,
      "xField": [
        "73b0e523-881e-41a6-bb8e-4f09d67592b9",
        "measure"
      ],
      "yField": "value",
      "seriesField": "measure",
      "barMaxWidth": 48,
      "barMinWidth": 8,
      "bar": {
        "style": {
          "cursor": "pointer"
        },
        "state": {
          "hover": {
            "stroke": "#3370FF",
            "lineWidth": 1
          }
        }
      },
      "label": {
        "visible": false,
        "position": "inside-top",
        "smartInvert": {
          "contrastRatiosThreshold": 2
        },
        "style": {
          "fontSize": 12,
          "lineHeight": 20,
          "fontWeight": 700,
          "fontFamily": "DIN Alternate",
          "stroke": ""
        },
        "overlap": {
          "strategy": []
        }
      }
    },
    {
      "type": "area",
      "id": "line",
      "dataIndex": 1,
      "animation": false,
      "xField": [
        "73b0e523-881e-41a6-bb8e-4f09d67592b9"
      ],
      "yField": "268a3dc9-bb14-45d7-aaf4-b8893a68784b",
      "stack": false,
      "point": {
        "style": {
          "size": 0,
          "fill": "#fff",
          "lineWidth": 2,
          "cursor": "pointer"
        },
        "state": {
          "dimension_hover": {
            "size": 8
          }
        }
      },
      "area": {
        "interactive": false,
        "visible": true,
        "style": {
          "fillOpacity": 0
        }
      },
      "label": {
        "visible": false,
        "style": {
          "fontSize": 12,
          "lineHeight": 20,
          "fontWeight": 700,
          "fontFamily": "DIN Alternate",
          "stroke": ""
        }
      },
      "line": {
        "style": {
          "curveType": "linear"
        }
      }
    }
  ],
  "region": [
    {
      "style": {
        "cursor": "pointer"
      }
    }
  ],
  "axes": [
    {
      "orient": "left",
      "seriesId": [
        "bar"
      ],
      "id": "axisLeft",
      "expand": {
        "max": 0.1
      },
      "title": {
        "text": "苹果销售额-整数 / 桃子销售额-浮点数",
        "visible": true,
        "style": {
          "fill": "#646A73",
          "fontSize": 12,
          "lineHeight": 20,
          "maxLineWidth": 234
        },
        "space": 8
      },
      "label": {
        "visible": true,
        "space": 8,
        "style": {
          "fill": "#646A73",
          "fontSize": 12,
          "lineHeight": 20,
          "maxLineWidth": 272.25
        }
      },
      "grid": {
        "style": {
          "lineDash": [
            3,
            3
          ]
        }
      }
    },
    {
      "orient": "right",
      "seriesId": [
        "line"
      ],
      "expand": {
        "max": 0.1
      },
      "sync": {
        "axisId": "axisLeft",
        "tickAlign": true
      },
      "visible": true,
      "title": {
        "text": "梨子销售额-定点数",
        "visible": true,
        "style": {
          "fill": "#646A73",
          "fontSize": 12,
          "lineHeight": 20,
          "maxLineWidth": 234
        },
        "space": 8
      },
      "label": {
        "visible": true,
        "space": 8,
        "style": {
          "fill": "#646A73",
          "fontSize": 12,
          "lineHeight": 20,
          "maxLineWidth": 272.25
        }
      }
    },
    {
      "orient": "bottom",
      "sampling": false,
      "title": {
        "text": "销售人名字-文本",
        "visible": true,
        "style": {
          "fill": "#646A73",
          "fontSize": 12,
          "lineHeight": 20,
          "maxLineWidth": 412.5
        },
        "space": 4
      },
      "label": {
        "visible": true,
        "autoRotate": true,
        "autoHide": false,
        "autoRotateAngle": [
          0,
          45
        ],
        "space": 6,
        "style": {
          "fill": "#646A73",
          "fontSize": 12,
          "lineHeight": 20,
          "maxLineWidth": 202.8
        }
      }
    }
  ],
  "tooltip": {
    "visible": true,
    "mark": {
      "content": {}
    },
    "dimension": {
      "content": {}
    },
    "minWidth": 120,
    "style": {
      "spaceRow": 2,
      "keyLabel": {
        "lineHeight": 20,
        "fontSize": 12,
        "textAlign": "left"
      },
      "valueLabel": {
        "lineHeight": 20,
        "fontSize": 12
      },
      "titleLabel": {
        "fontSize": 12,
        "lineHeight": 20,
        "fontColor": "#1F2329"
      },
      "panel": {
        "padding": {
          "top": 10,
          "bottom": 10,
          "left": 12,
          "right": 12
        },
        "border": {
          "color": "#EFF0F1",
          "width": 1,
          "radius": 6
        },
        "shadow": {
          "x": 0,
          "y": 4,
          "blur": 16,
          "spread": 4,
          "color": "#1F232908"
        }
      },
      "shape": {
        "size": 8,
        "spacing": 5
      }
    }
  },
  "crosshair": {
    "xField": {
      "visible": true
    }
  },
  "legends": {
    "visible": true,
    "interactive": true,
    "allowAllCanceled": true,
    "orient": "bottom",
    "position": "middle",
    "padding": {
      "top": 12
    },
    "maxRow": 1,
    "pager": {
      "padding": 0,
      "space": 0,
      "animation": false,
      "handler": {
        "space": 4,
        "preShape": "",
        "nextShape": "",
        "style": {
          "fill": "#8F959E",
          "size": 7
        },
        "state": {
          "hover": {
            "fill": "#336DF4"
          },
          "disable": {
            "fill": "#BBBFC4"
          }
        }
      },
      "textStyle": {
        "fill": "#8F959E",
        "fontSize": 12,
        "lineHeight": 20
      }
    },
    "item": {
      "spaceCol": 16,
      "spaceRow": 4,
      "background": {
        "state": {
          "selectedHover": {
            "fill": "#fff",
            "fillOpacity": "0.1"
          }
        }
      },
      "label": {
        "style": {
          "fontSize": 12,
          "lineHeight": 20,
          "maxLineWidth": 102.96000000000001,
          "fill": "#646A73"
        }
      },
      "shape": {
        "space": 2,
        "style": {
          "fillOpacity": 1
        }
      }
    }
  },
  "dataZoom": []
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

```

### PR DESCRIPTION
**Pull request by kkxxkk2019**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

closed #337, #357

### 🐞 Bugserver case id

64c9bd89fefb22d36622df5f
64c9bc84fefb22d36622df5d

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/data/transforms/legend-data/discrete/discrete.ts [hunk 1]
```diff
@@ -41,7 +42,7 @@ export const discreteLegendFilter = (data: Array<any>, op: IDiscreteLegendFilter
   selectedData.forEach(s => {
     selectedFilter[s] = true;
   });
-  const datumField = field();
+  const datumField = field() ?? DEFAULT_DATA_SERIES_FIELD;
```
Comment (xuefei1313) [inline packages/vchart/src/data/transforms/legend-data/discrete/discrete.ts:45]: 我看了下图例逻辑，这里获取 fields 的方法是图例从series上获取，是不是应该由series提供一个获取最终data_series_fields 的方法，并在里面做好兼容，而不是由外面这些模块去做判定呢？

**Review by xuefei1313 — APPROVED** [review]

File: packages/vchart/src/data/transforms/legend-data/discrete/discrete.ts (hunk 1 above)
Comment (kkxxkk2019) [reply packages/vchart/src/data/transforms/legend-data/discrete/discrete.ts:45]: 已添加 TODO comment, series 的 _seriesField 待统一
