### PR TITLE
fix: custom mark should run after all the series marks, fix #2156

### LINKED ISSUE #2156: [Bug] `customMark` 的回调上无法拿到 vgrammar 的语法图元，同 `extensionMark` 不一致
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

目前是这么使用的：

```ts
customMark: [
  {
    style: {
      x: (datum, ctx) => {
        return ctx.vchart.getChart().getAllSeries()[0].getMarkInName('bar').getProduct().elements; 
     }
    }
  }
]
```

### Current Behavior

`customMark`  ctx.vchart.getChart().getAllSeries()[0].getMarkInName('bar').getProduct().elements 始终为空

### Expected Behavior

可以获取到 elements

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xile611**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/custom-mark/custom-mark.ts [hunk 1]
```diff
@@ -54,16 +54,31 @@ export class CustomMark<T = any> extends BaseComponent<any> {
     if (!this._spec) {
       return;
     }
+    const series = this._option && this._option.getAllSeries();
+    const depend: IMark[] = [];
+
+    series &&
```
Comment (kkxxkk2019) [inline packages/vchart/src/component/custom-mark/custom-mark.ts:60]: series.length

**Review by kkxxkk2019 — APPROVED** [review]
