### PR TITLE
fix: remove scale.ticks()'s calling, becase it will change the scale'…

### LINKED ISSUE #2158: [Bug] 轴关闭并开启 onZero 之后，标注的定位发生错位
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

```ts
const spec = {
    direction: 'vertical',
    type: 'common',
    color: [
      '#61BA95',
      '#335B4A',
      '#7A94BF',
      '#2E5599',
      '#B9A582',
      '#735A40',
      '#BC9B44',
      '#99533D',
      '#809E9D',
      '#2E8582'
    ],
    series: [
      {
        type: 'bar',
        stack: true,
        bar: {
          state: {
            hover: {
              stroke: '#000',
              lineWidth: 1
            }
          }
        },
        label: {
          visible: true,
          position: 'inside',
          style: {
            lineHeight: '100%'
          },
          overlap: {
            strategy: []
          },
          smartInvert: {
            outsideEnable: true
          }
        },
        totalLabel: {
          visible: true,
          position: 'top',
          overlap: false,
          formatConfig: {
            fixed: 0
          },
          style: {
            lineHeight: '100%',
            lineWidth: 1,
            stroke: '#ffffff',
            fontSize: 14
          }
        },
        seriesLabel: {
          visible: true,
          position: 'end',
          label: {
            style: {
              lineHeight: '100%',
              lineWidth: 1,
              stroke: '#ffffff',
              fontSize: 16
            },
            space: 10
          }
        },
        xField: '_editor_dimension_field',
        yField: '_editor_value_field',
        dataId: '0',
        id: 'series-0',
        seriesField: '_editor_type_field'
      },
      {
        type: 'bar',
        stack: true,
        bar: {
          state: {
            hover: {
              stroke: '#000',
              lineWidth: 1
            }
          }
        },
        label: {
          visible: true,
          position: 'inside',
          style: {
            lineHeight: '100%'
          },
          overlap: {
            strategy: []
          },
          smartInvert: {
            outsideEnable: true
          }
        },
        totalLabel: {
          visible: true,
          position: 'top',
          overlap: false,
          formatConfig: {
            fixed: 0
          },
          style: {
            lineHeight: '100%',
            lineWidth: 1,
            stroke: '#ffffff',
            fontSize: 14
          }
        },
        seriesLabel: {
          visible: true,
          position: 'end',
          label: {
            style: {
              lineHeight: '100%',
              lineWidth: 1,
              stroke: '#ffffff',
              fontSize: 16
            },
            space: 10
          }
        },
        xField: '_editor_dimension_field',
        yField: '_editor_value_field',
        dataId: '1',
        id: 'series-1',
        seriesField: '_editor_type_field'
      },
      {
        type: 'bar',
        stack: true,
        bar: {
          state: {
            hover: {
              stroke: '#000',
              lineWidth: 1
            }
          }
        },
        label: {
          visible: true,
          position: 'inside',
          style: {
            lineHeight: '100%'
          },
          overlap: {
            strategy: []
          },
          smartInvert: {
            outsideEnable: true
          }
        },
        totalLabel: {
          visible: true,
          position: 'top',
          overlap: false,
          formatConfig: {
            fixed: 0
          },
          style: {
            lineHeight: '100%',
            lineWidth: 1,
            stroke: '#ffffff',
            fontSize: 14
          }
        },
        seriesLabel: {
          visible: true,
          position: 'end',
          label: {
            style: {
              lineHeight: '100%',
              lineWidth: 1,
              stroke: '#ffffff',
              fontSize: 16
            },
            space: 10
          }
        },
        xField: '_editor_dimension_field',
        yField: '_editor_value_field',
        dataId: '2',
        id: 'series-2',
        seriesField: '_editor_type_field'
      },
      {
        type: 'bar',
        stack: true,
        bar: {
          state: {
            hover: {
              stroke: '#000',
              lineWidth: 1
            }
          }
        },
        label: {
          visible: true,
          position: 'inside',
          style: {
            lineHeight: '100%'
          },
          overlap: {
            strategy: []
          },
          smartInvert: {
            outsideEnable: true
          }
        },
        totalLabel: {
          visible: true,
          position: 'top',
          overlap: false,
          formatConfig: {
            fixed: 0
          },
          style: {
            lineHeight: '100%',
            lineWidth: 1,
            stroke: '#ffffff',
            fontSize: 14
          }
        },
        seriesLabel: {
          visible: true,
          position: 'end',
          label: {
            style: {
              lineHeight: '100%',
              lineWidth: 1,
              stroke: '#ffffff',
              fontSize: 16
            },
            space: 10
          }
        },
        xField: '_editor_dimension_field',
        yField: '_editor_value_field',
        dataId: '3',
        id: 'series-3',
        seriesField: '_editor_type_field'
      }
    ],
    legends: {
      id: 'legend-discrete',
      visible: false,
      autoPage: false,
      position: 'start',
      interactive: false
    },
    region: [
      {
        id: 'region-0',
        style: {
          lineWidth: 1,
          stroke: 'red'
        }
      }
    ],
    tooltip: {
      visible: true
    },
    axes: [
      {
        orient: 'left',
        id: 'axis-left',
        type: 'linear',
        label: {
          autoLimit: false,
          formatMethod: null
        },
        autoIndent: false,
        maxWidth: null,
        maxHeight: null,
        visible: false
      },
      {
        orient: 'bottom',
        id: 'axis-bottom',
        type: 'band',
        label: {
          autoLimit: false
        },
        domainLine: {
          onZero: true
        },
        autoIndent: false,
        maxWidth: null,
        maxHeight: null,
        trimPadding: false
      }
    ],
    data: [
      {
        id: '0',
        sourceKey: 'China',
        values: [
          {
            _editor_dimension_field: '2000-2005',
            _editor_value_field: 430,
            _editor_type_field: 'China'
          },
          {
            _editor_dimension_field: '2015-2018',
            _editor_value_field: 1428,
            _editor_type_field: 'China'
          }
        ]
      },
      {
        id: '1',
        sourceKey: 'US',
        values: [
          {
            _editor_dimension_field: '2000-2005',
            _editor_value_field: 1386,
            _editor_type_field: 'US'
          },
          {
            _editor_dimension_field: '2015-2018',
            _editor_value_field: 1676,
            _editor_type_field: 'US'
          }
        ]
      },
      {
        id: '2',
        sourceKey: 'EU',
        values: [
          {
            _editor_dimension_field: '2000-2005',
            _editor_value_field: 860,
            _editor_type_field: 'EU'
          },
          {
            _editor_dimension_field: '2015-2018',
            _editor_value_field: 993,
            _editor_type_field: 'EU'
          }
        ]
      },
      {
        id: '3',
        sourceKey: 'Rest of World',
        values: [
          {
            _editor_dimension_field: '2000-2005',
            _editor_value_field: 2103,
            _editor_type_field: 'Rest of World'
          },
          {
            _editor_dimension_field: '2015-2018',
            _editor_value_field: 2111,
            _editor_type_field: 'Rest of World'
          }
        ]
      }
    ],
    markArea: [],
    markLine: [
      {
        id: '26491f4e-2f0a-49a9-8656-e639db6308bb',
        interactive: true,
        name: 'total-diff-line',
        type: 'type-step',
        coordinates: [
          {
            _editor_dimension_field: '2000-2005',
            _editor_value_field: 4779,
            _editor_type_field: 'Rest of World',
            __VCHART_DEFAULT_DATA_INDEX: 0,
            __VCHART_DEFAULT_DATA_KEY: 0,
            __VCHART_STACK_END: 4779,
            __VCHART_STACK_START: 2676,
            __VCHART_STACK_START_PERCENT: 0.5599497802887633,
            __VCHART_STACK_END_PERCENT: 1,
            __VCHART_STACK_TOTAL: 4779,
            __VCHART_STACK_TOTAL_PERCENT: 1,
            __VCHART_STACK_TOTAL_TOP: true,
            VGRAMMAR_DATA_ID_KEY_229: 0,
            refRelativeSeriesId: 'series-3'
          },
          {
            _editor_dimension_field: '2015-2018',
            _editor_value_field: 6208,
            _editor_type_field: 'Rest of World',
            __VCHART_DEFAULT_DATA_INDEX: 1,
            __VCHART_DEFAULT_DATA_KEY: 1,
            __VCHART_STACK_END: 6208,
            __VCHART_STACK_START: 4097,
            __VCHART_STACK_START_PERCENT: 0.6599548969072165,
            __VCHART_STACK_END_PERCENT: 1,
            __VCHART_STACK_TOTAL: 6208,
            __VCHART_STACK_TOTAL_PERCENT: 1,
            __VCHART_STACK_TOTAL_TOP: true,
            VGRAMMAR_DATA_ID_KEY_229: 1,
            refRelativeSeriesId: 'series-3'
          }
        ],
        connectDirection: 'top',
        expandDistance: '15.957446808510639%',
        line: {
          style: {
            stroke: '#000',
            lineWidth: 1,
            pickStrokeBuffer: 16,
            lineDash: [0],
            cornerRadius: 4
          }
        },
        label: {
          position: 'middle',
          text: '30%',
          labelBackground: {
            style: {
              fill: '#fff',
              fillOpacity: 1,
              stroke: '#000',
              lineWidth: 1,
              cornerRadius: 4
            }
          },
          style: {
            fill: '#000'
          },
          pickable: true,
          childrenPickable: false
        },
        endSymbol: {
          size: 10,
          refX: -4,
          style: {
            fill: '#000',
            lineWidth: 0,
            stroke: null
          }
        },
        _originValue_: [4779, 6208],
        zIndex: 510,
        coordinatesOffset: [
          {
            x: 0,
            y: -18.000000000000007
          },
          {
            x: 0,
            y: -18
          }
        ]
      }
    ],
    width: 640,
    height: 360,
    background: 'transparent'
  };
```

### Current Behavior

NA

### Expected Behavior

NA

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by kkxxkk2019**
…s domain

[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #2158 

### 🐞 Bugserver case id

65b372ceeb5358008d749074

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/axis/polar/axis.ts [hunk 1]
```diff
@@ -547,7 +531,7 @@ export abstract class PolarAxis<T extends IPolarAxisCommonSpec = IPolarAxisCommo
         type: this._spec.grid?.smooth ? 'circle' : 'polygon',
         center,
         closed: true,
-        sides: this._getRelatedAngleAxis()?.tickValues().length,
```
Comment (xile611) [inline packages/vchart/src/component/axis/polar/axis.ts:550]: 这个地方不能用 domain()，因为要拿 角度轴刻度的个数

**Review by xile611 — APPROVED** [review]
