### PR TITLE
Fix/data zoom span

### LINKED ISSUE #2195: [Bug] maxSpan of Datazoom not work
### Version

1.9.0

### Link to Minimal Reproduction

no need

### Steps to Reproduce

img_v3_027k_9736bfd4-568a-4e8a-b488-12e1150a0c9g

### Current Behavior

设置 maxSpan 后缩略轴仍可拖动大于最大值

### Expected Behavior

maxSpan 正常生效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by skie1997**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #2195 

### 🐞 Bugserver case id
fileid=6511e1ee172872291c4615d5&interactionid=65bb3cf3a5bf73008c9ba7ab

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/data-zoom/data-zoom/data-zoom.ts [hunk 1]
```diff
@@ -338,25 +338,27 @@ export class DataZoom<T extends IDataZoomSpec = IDataZoomSpec> extends DataFilte
 
   protected _handleChange(start: number, end: number, updateComponent?: boolean, tag?: string) {
     super._handleChange(start, end, updateComponent);
-    if (updateComponent && this._component) {
-      this._component.setStartAndEnd(start, end);
-    }
+    if (this._shouldChange) {
```
Comment (xile611) [inline packages/vchart/src/component/data-zoom/data-zoom/data-zoom.ts:341]: `_shouldChange` 为`false` 的时候，`super._handleChange()` 还需要调用吗

**Review by xile611 — APPROVED** [review]
