### PR TITLE
fix: optimize visual effect for duplicated funnel data

### LINKED ISSUE #1921: [Bug] 漏斗图数据显示缺失
### Version

1.8.1

### Link to Minimal Reproduction

none

### Steps to Reproduce

```
 const spec = {
    "type": "funnel",
    "padding": 0,
    "shape": "rect",
    "categoryField": "10001",
    "valueField": "10002",
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "10001": "雇佣类型",
                    "10002": "7",
                    "10003": "job_recruitment_type12d1be0f_c261_425a_bbb3_a750f655eed0",
                    "job_recruitment_type12d1be0f_c261_425a_bbb3_a750f655eed0": "7",
                    "transfer": null,
                    "baseTransfer": 1
                },
                {
                    "10001": "职位新建时间",
                    "10002": "23",
                    "10003": "job_biz_create_time813bbdf1_07fe_4924_8a60_7ef4f506305c",
                    "job_biz_create_time813bbdf1_07fe_4924_8a60_7ef4f506305c": "23",
                    "transfer": 3.2857142857142856,
                    "baseTransfer": 3.2857142857142856
                },
                {
                    "10001": "职位到期日期",
                    "10002": "11",
                    "10003": "job_biz_expired_time8f0046be_363b_4ee6_b2cb_3cef5a56a867",
                    "job_biz_expired_time8f0046be_363b_4ee6_b2cb_3cef5a56a867": "11",
                    "transfer": 0.4782608695652174,
                    "baseTransfer": 1.5714285714285714
                },
                {
                    "10001": "职位关闭日期",
                    "10002": "5",
                    "10003": "job_biz_close_timed1468cbb_ed8b_4dba_a4c3_6a53c7693b78",
                    "job_biz_close_timed1468cbb_ed8b_4dba_a4c3_6a53c7693b78": "5",
                    "transfer": 0.45454545454545453,
                    "baseTransfer": 0.7142857142857143
                },
                {
                    "10001": "职位到期日期",
                    "10002": "11",
                    "10003": "job_biz_expired_time1cef3afa_0a3d_45b7_8c72_ec59a54447c6",
                    "job_biz_expired_time1cef3afa_0a3d_45b7_8c72_ec59a54447c6": "11",
                    "transfer": 2.2,
                    "baseTransfer": 1.5714285714285714
                },
                {
                    "10001": "序列adas",
                    "10002": 23,
                    "10003": "job_family8213506a_943e_4b64_9a3b_73e588503539",
                    "job_family8213506a_943e_4b64_9a3b_73e588503539": "23",
                    "transfer": 2.090909090909091,
                    "baseTransfer": 3.2857142857142856
                }
            ],
           
        }
    ],
    "isTransform": true,

    // "seriesField": "10001",
    "color": {
        "field": "10001",
        "type": "ordinal",
        "range": [
            "#3370EB",
            "#25B2E5",
            "#1bcebf",
            "#27ad8e",
            "#bf78e9"
        ],
        "specified": {}
    },
    // "legends": [
    //     {
    //         "type": "discrete",
    //         "visible": true,
    //         "id": "legend-discrete",
    //         "orient": "bottom",
    //         "position": "middle",
    //         "layoutType": "normal",
    //         "maxRow": 2,
    //         "title": {
    //             "textStyle": {
    //                 "fontSize": 12,
    //                 "fill": "#6F6F6F"
    //             }
    //         },
    //         "layoutLevel": 50,
    //         "item": {
    //             "focus": false,
    //             "focusIconStyle": {
    //                 "size": 14
    //             },
    //             "maxWidth": 400,
    //             "spaceRow": 0,
    //             "spaceCol": 0,
    //             "padding": {
    //                 "top": 4,
    //                 "bottom": 4,
    //                 "left": 4,
    //                 "right": 22
    //             },
    //             "background": {
    //                 "visible": false,
    //                 "style": {
    //                     "fillOpacity": 0.001
    //                 }
    //             },
    //             "label": {
    //                 "style": {
    //                     "fontSize": 12,
    //                     "fill": "#6F6F6F"
    //                 }
    //             },
    //             "shape": {
    //                 "style": {
    //                     "lineWidth": 0,
    //                     "symbolType": "square"
    //                 }
    //             }
    //         },
    //         "pager": {
    //             "layout": "horizontal",
    //             "padding": 0,
    //             "textStyle": {},
    //             "space": 0,
    //             "handler": {
    //                 "preShape": "triangleLeft",
    //                 "nextShape": "triangleRight",
    //                 "style": {},
    //                 "state": {
    //                     "disable": {}
    //                 }
    //             }
    //         },
    //         "padding": {
    //             "top": 16,
    //             "bottom": 0,
    //             "left": 0,
    //             "right": 0
    //         }
    //     }
    // ],
    // "label": {
    //     "visible": true,
    //     "offset": 0,
    //     "overlap": {
    //         "hideOnHit": true,
    //         "avoidBaseMark": false,
    //         "strategy": [
    //             {
    //                 "type": "position",
    //                 "position": [
    //                     "top",
    //                     "bottom"
    //                 ]
    //             },
    //             {
    //                 "type": "moveY",
    //                 "offset": [
    //                     -10,
    //                     -9,
    //                     -8,
    //                     -7,
    //                     -6,
    //                     -5,
    //                     -4,
    //                     -3,
    //                     -2,
    //                     -1,
    //                     0,
    //                     1,
    //                     2,
    //                     3,
    //                     4,
    //                     5,
    //                     6,
    //                     7,
    //                     8,
    //                     9,
    //                     10
    //                 ]
    //             },
    //             {
    //                 "type": "moveX",
    //                 "offset": [
    //                     -10,
    //                     -9,
    //                     -8,
    //                     -7,
    //                     -6,
    //                     -5,
    //                     -4,
    //                     -3,
    //                     -2,
    //                     -1,
    //                     0,
    //                     1,
    //                     2,
    //                     3,
    //                     4,
    //                     5,
    //                     6,
    //                     7,
    //                     8,
    //                     9,
    //                     10
    //                 ]
    //             }
    //         ],
    //         "clampForce": true
    //     },
    //     "style": {
    //         "fontSize": 14,
    //         "fontFamily": "Din alternate, Din pro",
    //         "zIndex": 400,
    //         "lineHeight": "100%",
    //         "fill": "#363839",
    //         "lineWidth": 1,
    //         "strokeOpacity": 1
    //     },
    //     "smartInvert": {
    //         "fillStrategy": "invertBase",
    //         "strokeStrategy": "similarBase",
    //         "outsideEnable": false
    //     }
    // },
    // "outerLabel": {
    //     "visible": true,
    //     "style": {
    //         "fontSize": 14,
    //         "fill": "#9ca0b1"
    //     },
    //     "line": {
    //         "style": {
    //             "stroke": "#9ca0b1"
    //         }
    //     }
    // },
    "hover": {
        "enable": true
    },
    "select": false,
    // "funnel": {
    //     "state": {
    //         "hover": {
    //             "cursor": "pointer",
    //             "fillOpacity": 0.8,
    //             "stroke": "#58595B",
    //             "lineWidth": 1,
    //             "zIndex": 500
    //         },
    //         "selected": {
    //             "cursor": "pointer",
    //             "fillOpacity": 1,
    //             "stroke": "#58595B",
    //             "lineWidth": 1
    //         },
    //         "selected_reverse": {
    //             "fillOpacity": 0.3,
    //             "strokeWidth": 0.3
    //         }
    //     },
    //     "style": {
    //         "lineWidth": 1
    //     }
    // },
    "tooltip": {
        "handler": {}
    },
    // "region": [
    //     {
    //         "clip": true
    //     }
    // ],
    "background": "rgba(255, 255, 255, 0)",
    "animation": false,
    "hash": "15c4e9cb621f215f2f88d373ca9c156c"
}

 const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

### Current Behavior

缺少一个数据展示

### Expected Behavior

展示正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xiaoluoHe**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
closes #1921 

### 🐞 Bugserver case id
65967ff92a62f50097e23e44

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/series/funnel/funnel.ts [hunk 1]
```diff
@@ -483,6 +480,12 @@ export class FunnelSeries<T extends IFunnelSeriesSpec = IFunnelSeriesSpec>
     if (this._funnelAlign !== 'center') {
       this._adjustPoints(points);
     }
+
```
Comment (xile611) [inline packages/vchart/src/series/funnel/funnel.ts:483]: 调试代码需要删掉

**Review by xile611 — CHANGES_REQUESTED** [review]

File: packages/vchart/src/series/funnel/funnel.ts (hunk 1 above)
Comment (xiaoluoHe) [reply packages/vchart/src/series/funnel/funnel.ts:483]: 阿这，尴尬，我的

**Review by xile611 — APPROVED** [review]
