### PR TITLE
Fix/multiple axis

### LINKED ISSUE #2178: [Bug]  多层标签通过 layers 关闭所有轴标签，图表报错
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

```ts
const spec = {
    "type": "bar",
    "yField": "value",
    "stack": false,
    "label": {
        "visible": true,
        "position": "outside"
    },
    "legends": [
        {
            "visible": true,
        }
    ],
    "xField": [
        "filterKey",
        "type"
    ],
    "seriesField": "filterKey",
    "axes": [
        {
            "orient": "bottom",
            "visible": true,
            "showAllGroupLayers": true,
            "layers": [
                {
                    "visible": false
                },
                {
                    "visible": false
                }
            ],
            "label": {
                "visible": true
            }
        },
        {
            "orient": "left",
            "visible": true,
            "zero": false,
            "label": {
                "visible": true
            }
        }
    ],
    "data": [
        {
            "name": "bar",
            "values": [
                {
                    "type": "normal",
                    "filterKey": "非首日（1）",
                    "value": 3531,
                },
                {
                    "type": "compare",
                    "filterKey": "非首日（1）",
                    "value": 3530,
                },
                {
                    "type": "normal",
                    "filterKey": "已登录（2）",
                    "value": 0,
                },
                {
                    "type": "compare",
                    "filterKey": "已登录（2）",
                    "value": 0,
                }
            ]
        }
    ],
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

### Current Behavior

NA

### Expected Behavior

NA

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### LINKED ISSUE #2179: [Bug] 轴多层标签关闭非第一层标签，轴标签不绘制
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

```ts
  const spec = {
    type: 'bar',
    data: [
      {
        values: [
          {
            type: 'Category One',
            min: 76,
            max: 100,
            range: 'A',
            type2: 'p',
            color: 'A_p'
          },
          {
            type: 'Category Two',
            min: 56,
            max: 108,
            range: 'A',
            type2: 'p',
            color: 'A_p'
          },
          {
            type: 'Category One',
            min: 56,
            max: 100,
            range: 'B',
            type2: 'p',
            color: 'B_p'
          },
          {
            type: 'Category Two',
            min: 36,
            max: 108,
            range: 'B',
            type2: 'p',
            color: 'B_p'
          },

          {
            type: 'Category One',
            min: 76,
            max: 100,
            range: 'A',
            type2: 'k',
            color: 'A_k'
          },
          {
            type: 'Category Two',
            min: 56,
            max: 108,
            range: 'A',
            type2: 'k',
            color: 'A_k'
          },
          {
            type: 'Category One',
            min: 56,
            max: 100,
            range: 'B',
            type2: 'k',
            color: 'B_k'
          },
          {
            type: 'Category Two',
            min: 36,
            max: 108,
            range: 'B',
            type2: 'k',
            color: 'B_k'
          }
        ]
      }
    ],
    xField: ['type', 'range', 'type2'],
    yField: 'min',
    seriesField: 'color',
    // barGapInGroup: [0, 5],
    barWidth: 20,
    paddingInner: [0.6, 0.6, 0.6],
    bandPadding: [0.6, 0.6, 0.6],
    label: {
      position: 'bothEnd'
    },
    axes: [
      {
        orient: 'bottom',
        showAllGroupLayers: true,
        layers: [
          {
            visible: true
          },
          {
            visible: false
            // tickCount: 2
          },
          {
            visible: false
          }
        ],
        // sampling: false,
        label: {
          // autoRotate: true
        },
        tick: {
          tickCount: 2
        }
      }
    ],
    legends: {
      visible: true
    }
  };

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

### Current Behavior

image

### Expected Behavior

绘制第一层标签

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by kkxxkk2019**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

closed #2178 
closed #2179 

### 🐞 Bugserver case id

65b8ca18c00fc9008c750044
65b8ca75c00fc9008c750045

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/axis/mixin/band-axis-mixin.ts [hunk 1]
```diff
@@ -161,32 +161,54 @@ export class BandAxisMixin {
...
     const labelItems: Dict<any>[][] = [];
     let preData: any[] = [];
-    this._tickData.forEach((eachTickData, index) => {
-      const latestData = eachTickData.getLatestData();
-      if (latestData && latestData.length) {
+
+    this._scales.forEach((scale, index) => {
+      // 通过名称查找对应的 tickData
+      const tickData = this._tickData.find(child => {
+        const dataViewName = child.getDataView().name as string;
```
Comment (xile611) [inline packages/vchart/src/component/axis/mixin/band-axis-mixin.ts:168]: 通过`name` 查找的话，这个规则会不会太不 **明显** 了，要不要通过**显示**的属性关联起来？

Comment (kkxxkk2019) [reply packages/vchart/src/component/axis/mixin/band-axis-mixin.ts:168]: 嗯，这个规则其实是明显的，不过确实有点 hack，但是主要是目前 DataView 没有**显示**的属性关联

**Review by xile611 — APPROVED** [review]
