### PR TITLE
Fix/scroll axis label

### LINKED ISSUE #2534: [Bug] axes label position is wrong after scrolling
### Version

1.8.7

### Link to Minimal Reproduction

null

### Steps to Reproduce

```
const spec = {
  "type": "bar",
  "direction": "horizontal",
  "legends": [
    {
      "visible": true,
      "type": "discrete",
      "orient": "bottom"
    }
  ],
  "label": {
    "visible": false
  },
  "theme": {
    "colorScheme": {
      "default": [
        "#1664FF",
        "#3CC780",
        "#FF8A00",
        "#1AC6FF",
        "#7442D4",
        "#FFC400",
        "#B48DEB",
        "#009488",
        "#304D77",
        "#FF7DDA"
      ]
    }
  },
  "bar": {
    "style": {
      "fillOpacity": 1
    },
    "state": {
      "hover": {
        "stroke": "#898989",
        "lineWidth": 1
      }
    }
  },
  "padding": {
    "top": 0,
    "left": 0,
    "bottom": 0,
    "right": 0
  },
  "region": [
    {
      "clip": true
    }
  ],
  "barWidth": 10,
  "barGapInGroup": 10,
  "xField": "metrics",
  "yField": "dimension",
  "stack": true,
  "seriesField": "group",
  animation: false,
  "axes": [
    {
      "orient": "bottom",
      "title": "",
      "label": {
        "padding": 6
      }
    },
    {
      "orient": "left",
      "title": "",
      "bandSize": 95,
      "label": {
        "padding": 6
      }
    }
  ],
  "data": [
    {
      "id": "barData",
      "values": [
        {
          "dimension": "回合1",
          "metrics": 21,
          "originData": {
            "x": "回合1",
            "y": 21,
            "c": "绿水灵"
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合1",
          "metrics": 38,
          "originData": {
            "x": "回合1",
            "y": 38,
            "c": "飘飘猪"
          },
          "group": "飘飘猪"
        },
        {
          "dimension": "回合2",
          "metrics": 28,
          "originData": {
            "x": "回合2",
            "y": 28,
            "c": "绿水灵"
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合2",
          "metrics": 45,
          "originData": {
            "x": "回合2",
            "y": 45,
            "c": "飘飘猪"
          },
          "group": "飘飘猪"
        },
        {
          "dimension": "回合3",
          "metrics": 22,
          "originData": {
            "x": "回合3",
            "y": 22,
            "c": "绿水灵"
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合3",
          "metrics": 56,
          "originData": {
            "x": "回合3",
            "y": 56,
            "c": "飘飘猪"
          },
          "group": "飘飘猪"
        },
        {
          "dimension": "回合4",
          "metrics": 34,
          "originData": {
            "x": "回合4",
            "y": 34,
            "c": "绿水灵"
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合4",
          "metrics": 48,
          "originData": {
            "x": "回合4",
            "y": 48,
            "c": "飘飘猪"
          },
          "group": "飘飘猪"
        },
        {
          "dimension": "回合5",
          "metrics": 34,
          "originData": {
            "x": "回合5",
            "y": 34,
            "c": "绿水灵"
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合5",
          "metrics": 64,
          "originData": {
            "x": "回合5",
            "y": 64,
            "c": "飘飘猪"
          },
          "group": "飘飘猪"
        },
        {
          "dimension": "回合6",
          "metrics": 44,
          "originData": {
            "x": "回合6",
            "y": 44,
            "c": "绿水灵",
            "latest": true
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合6",
          "metrics": 72,
          "originData": {
            "x": "回合6",
            "y": 72,
            "c": "飘飘猪",
            "latest": true
          },
          "group": "飘飘猪"
        },
        {
          "dimension": "回合7",
          "metrics": 38,
          "originData": {
            "x": "回合7",
            "y": 38,
            "c": "绿水灵",
            "latest": true
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合7",
          "metrics": 65,
          "originData": {
            "x": "回合7",
            "y": 65,
            "c": "飘飘猪",
            "latest": true
          },
          "group": "飘飘猪"
        },
        {
          "dimension": "回合8",
          "metrics": 24,
          "originData": {
            "x": "回合8",
            "y": 24,
            "c": "绿水灵",
            "latest": true
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合8",
          "metrics": 70,
          "originData": {
            "x": "回合8",
            "y": 70,
            "c": "飘飘猪",
            "latest": true
          },
          "group": "飘飘猪"
        },
        {
          "dimension": "回合9",
          "metrics": 28,
          "originData": {
            "x": "回合9",
            "y": 28,
            "c": "绿水灵",
            "latest": true
          },
          "group": "绿水灵"
        },
        {
          "dimension": "回合9",
          "metrics": 62,
          "originData": {
            "x": "回合9",
            "y": 62,
            "c": "飘飘猪",
            "latest": true
          },
          "group": "飘飘猪"
        }
      ]
    }
  ],
  "scrollBar": [
    {
      "orient": "right",
      // start: 0,
      // end: 0.2,
      // filterMode: 'filter',
      "roam": true,
      // delayType: 'throttle',
      // delayTime: 500
      "auto": false
    }
  ]
};
```

### Current Behavior

image

### Expected Behavior

image

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by skie1997**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #2534 

### 🐞 Bugserver case id
6612cd5e86f3f400b6d65006

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/axis/cartesian/axis.ts [hunk 1]
```diff
@@ -779,9 +760,26 @@ export abstract class CartesianAxis<T extends ICartesianAxisCommonSpec = ICartes
...
       });
+      // 过程: dolayout -> getBoundsInRect: update tick attr -> forceLayout ->  updateLayoutAttr: update tick attr -> chart layout -> scale update -> mark encode
+      // 问题: chart layout之后, scale发生变化, 导致tick 和 mark position 不同步
+      // 解决方案: chart layout 之后重新计算tick位置
+      this.event.on(ChartEvent.layoutEnd, this._updateAxisLayout);
     }
   }
 
+  protected _updateAxisLayout = () => {
+    const startPoint = this.getLayoutStartPoint();
```
Comment (xile611) [inline packages/vchart/src/component/axis/cartesian/axis.ts:771]:
```
if (!this.visible) {
      return;
    }
```
这段还是要保留吧

**Review by xuefei1313 — APPROVED** [review]
