### PR TITLE
Fix/treemap legend filter

### LINKED ISSUE #2749: [Bug] incorrect result when sliding treemap colorLegend
### Version

1.11.1

### Link to Minimal Reproduction

--

### Steps to Reproduce

```
const spec = {
  type: "treemap",
  categoryField: "name",
  valueField: "value",
  roam: false,
  splitType: false,
  data: [
    {
      id:'0',
      values: [
        {
          name: "A",
          children: [
            {
              value: 1,
              value1: "100",
              name: "内蒙古",
              dataItem: {
                value: 1,
                value1: "100",
                name: "内蒙古",
              },
              metaItem: {
                dataIndex: "value",
                type: "number",
                title: "曝光UV",
              },
              meta: [
                {
                  dataIndex: "name",
                  type: "string",
                  analysisType: "dimension",
                  title: "省份",
                },
                {
                  dataIndex: "value",
                  type: "number",
                  title: "曝光UV",
                },
                {
                  dataIndex: "value1",
                  type: "number",
                  title: "用户数",
                },
              ],
              $$title: "内蒙古",
              $$value: 1,
            },
            {
              value: 2,
              name: "江苏",
              value1: "132",
              dataItem: {
                value: 2,
                name: "江苏",
                value1: "132",
              },
              metaItem: {
                dataIndex: "value",
                type: "number",
                title: "曝光UV",
              },
              meta: [
                {
                  dataIndex: "name",
                  type: "string",
                  analysisType: "dimension",
                  title: "省份",
                },
                {
                  dataIndex: "value",
                  type: "number",
                  title: "曝光UV",
                },
                {
                  dataIndex: "value1",
                  type: "number",
                  title: "用户数",
                },
              ],
              $$title: "江苏",
              $$value: 2,
            },
            {
              value: 3,
              name: "山东",
              value1: "122",
              dataItem: {
                value: 3,
                name: "山东",
                value1: "122",
              },
              metaItem: {
                dataIndex: "value",
                type: "number",
                title: "曝光UV",
              },
              meta: [
                {
                  dataIndex: "name",
                  type: "string",
                  analysisType: "dimension",
                  title: "省份",
                },
                {
                  dataIndex: "value",
                  type: "number",
                  title: "曝光UV",
                },
                {
                  dataIndex: "value1",
                  type: "number",
                  title: "用户数",
                },
              ],
              $$title: "山东",
              $$value: 3,
            },
            {
              value: 4,
              name: "河南",
              value1: "112",
              dataItem: {
                value: 4,
                name: "河南",
                value1: "112",
              },
              metaItem: {
                dataIndex: "value",
                type: "number",
                title: "曝光UV",
              },
              meta: [
                {
                  dataIndex: "name",
                  type: "string",
                  analysisType: "dimension",
                  title: "省份",
                },
                {
                  dataIndex: "value",
                  type: "number",
                  title: "曝光UV",
                },
                {
                  dataIndex: "value1",
                  type: "number",
                  title: "用户数",
                },
              ],
              $$title: "河南",
              $$value: 4,
            },
          ],
        },
      ],
    },
  ],
  label: {
    visible: true,
    style: {},
  },
  leaf: {
    style: {
      fill: {
        field: "value",
        scale: "color",
      },
    },
  },
  leaf: {
    style: {
      fill: {
        field: "value",
        scale: "color",
      },
    },
  },
  color: {
    type: "linear",
     domain: [
      {
        dataId: '0',
        fields: ['value']
      }
    ],
    range: ["#b2e3ff", "#0050b3"],
  },
  legends: {
    type: "color",
    visible: true,
    orient: "top",
    position: "start",
    title: {
      visible: false,
      textStyle: {
        fontSize: 12,
      },
    },
    field: "value",
  },
  tooltip: {
    visible: true,
    mark: {
      visible: true,
    },
    dimension: {
      visible: false,
    },
    titleStyle: {},
    contentStyle: {},
  },
  crosshair: {
    xField: {
      visible: true,
    },
  },
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window["vchart"] = vchart;
```

### Current Behavior

image

### Expected Behavior

正常筛选

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xiaoluoHe**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
closes #2749 

### 🐞 Bugserver case id
665d954d46251700ade1e77f

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/data/transforms/legend-data/continuous/continuous.ts [hunk 1]
```diff
@@ -34,10 +36,13 @@ export const continuousLegendDataMake = (data: Array<ISeries>, op: IContinuousLe
...
 // 连续数据过滤
 export const continuousLegendFilter = (data: Array<any>, op: IContinuousLegendFilterOption) => {
-  const { selected, field, data: legendData } = op;
+  const { selected, field, data: legendData, isHierarchyData } = op;
   const selectedRange = selected();
   const datumField = field();
   const dataRange = legendData();
+  const isHierarchy = isHierarchyData
+    ? isHierarchyData
+    : (data: Array<any>) => data && data.every(d => d && isArray(d.children));
```
Comment (xile611) [inline packages/vchart/src/data/transforms/legend-data/continuous/continuous.ts:45]: `!isNil(d.children) || isArray(d.children);`
 是不是要兼容，部分children 为空的情况？

File: packages/vchart/src/util/hierarchy.ts [hunk 2]
```diff
@@ -93,3 +93,35 @@ export const findHierarchyPath = <T>(
   dfs(hierarchyData, []);
   return result;
 };
+
+export function filterHierarchyDataByRange(
```
Comment (xile611) [inline packages/vchart/src/util/hierarchy.ts:97]: 这种方法可以补充一下本地的单测

**Review by xile611 — APPROVED** [review]
