### PR TITLE
fix(vchart): fix the duplicate event registration in scrollbar, fixed…

### LINKED ISSUE #1241: [Bug] 飞书小程序使用 vchart 折线图开启scrollbar 滚动条之后拖拽卡顿
### Version

"@visactor/lark-vchart": "1.5.1-alpha.0"

### Link to Minimal Reproduction

null

### Steps to Reproduce

```
const  spec={
      type: "line",
      width: 360,
      height: 340,
      padding: {
        top: "8%"
      },
      data: {
        values: [
          { date: "第1日", value: 9629, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第1日", value: 97669, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第1日", value: 5572, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第2日", value: 4652, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第2日", value: 32454, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第2日", value: 3688, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第3日", value: 3807, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第3日", value: 16182, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第3日", value: 3109, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第4日", value: 2167, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第4日", value: 2001, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第4日", value: 7454, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第5日", value: 1599, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第5日", value: 5281, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第5日", value: 3257, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第6日", value: 1487, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第6日", value: 3147, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第6日", value: 1952, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第7日", value: 1440, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第7日", value: 1611, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第7日", value: 1956, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第8日", value: 1662, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第8日", value: 2021, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第8日", value: 1915, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第9日", value: 2056, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第9日", value: 2592, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第9日", value: 2595, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第10日", value: 2028, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第10日", value: 1089, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第10日", value: 2364, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第11日", value: 959, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第11日", value: 687, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第11日", value: 1427, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第12日", value: 869, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第12日", value: 9172, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第12日", value: 1437, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第13日", value: 1354, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第13日", value: 885, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第13日", value: 571, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第14日", value: 193, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第14日", value: 1372, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第14日", value: 767, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第15日", value: 930, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第15日", value: 144, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第15日", value: 1127, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第16日", value: 1358, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第16日", value: 92, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第16日", value: 2074, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第17日", value: 1520, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第17日", value: 103, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第17日", value: 1794, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第18日", value: 664, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第18日", value: 843, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第18日", value: 140, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第19日", value: 695, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第19日", value: 6728, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第19日", value: 684, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第20日", value: 882, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第20日", value: 508, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第20日", value: 827, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第21日", value: 1114, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第21日", value: 298, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第21日", value: 914, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第22日", value: 1398, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第22日", value: 575, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第22日", value: 1143, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第23日", value: 5820, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第23日", value: 2153, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第23日", value: 1457, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第24日", value: 1596, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第24日", value: 2627, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第24日", value: 1880, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第25日", value: 1508, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第25日", value: 1559, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第25日", value: 588, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第26日", value: 1316, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第26日", value: 1102, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第26日", value: 738, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第27日", value: 660, type: "迪士尼100周年公主小时候系列手办" },
          { date: "第27日", value: 1143, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第27日", value: 1214, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第28日", value: 1114, type: "DIMOO：今晚不准睡系列-盲盒挂件" },
          { date: "第28日", value: 1500, type: "泡泡萌粒 迷你冰棒系列公仔" },
          { date: "第28日", value: 750, type: "迪士尼100周年公主小时候系列手办" }
        ]
      },
      scrollBar: [
        {
          orient: 'bottom',
          startValue: "第1日",
          endValue: "第10日",
          // roam: true
        }
      ],
      legends: {
        visible: true,
      },
      xField: 'date',
      yField: 'value',
      seriesField: 'type',
    }
const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();
// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

### Current Behavior

https://github.com/VisActor/VChart/assets/40026218/452ee331-f883-4975-b046-41254e3ae2bf

### Expected Behavior

No lag when dragging

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by kkxxkk2019**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

closed #1241 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/data-zoom/scroll-bar/scroll-bar.ts [hunk 1]
```diff
@@ -104,7 +104,14 @@ export class ScrollBar<T extends IScrollBarSpec = IScrollBarSpec> extends DataFi
         direction: this._isHorizontal ? 'horizontal' : 'vertical',
         ...this._getComponentAttrs()
       });
-
+      // 绑定事件，防抖，防止频繁触发
```
Comment (skie1997) [inline packages/vchart/src/component/data-zoom/scroll-bar/scroll-bar.ts:107]: 升级vrender-components之后支持配置防抖和节流。也可以先合入，我在我的MR里再去掉

**Review by skie1997 — APPROVED** [review]

File: packages/vchart/src/component/data-zoom/scroll-bar/scroll-bar.ts (hunk 1 above)
Comment (kkxxkk2019) [reply packages/vchart/src/component/data-zoom/scroll-bar/scroll-bar.ts:107]: OK~
