### PR TITLE
fix: typed chart cannot enable progressive render

### LINKED ISSUE #228: [Bug] progressive render config not work in line chart
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

1. configure large data in `line` chart;
2. configure progressive render config;

### Current Behavior

progressive rendering not work

### Expected Behavior

enable progressive rendering 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xiaoluoHe**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #228 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/chart/base-chart.ts [hunk 1]
```diff
@@ -930,7 +930,12 @@ export class BaseChart extends CompilableBase implements IChart {
       animationExit: spec.animationExit,
       animationNormal: spec.animationNormal,
 
-      extensionMark: spec.extensionMark
+      extensionMark: spec.extensionMark,
```
Comment (kkxxkk2019) [inline packages/vchart/src/chart/base-chart.ts:933]: 类型定义需要补充上

**Review by kkxxkk2019 — APPROVED** [review]
