### PR TITLE
Fix/rose tooltip

### LINKED ISSUE #1263: [Bug] RoseChart, Tooltip Error.
Image

```ts
{
    "type": "rose",
    "categoryField": "20001",
    "valueField": "10002",
    "seriesField": "20001",
    "padding": 0,
    "axes": [
        {
            "orient": "radius",
            "zero": true,
            "nice": false
        }
    ],
    "data": [
        {
            "id": "data",
            "values": [
                {
                    "10001": "数_量",
                    "10002": "37534",
                    "10003": "231021185249544",
                    "20001": "数_量",
                    "231021185249544": "37534"
                },
                {
                    "10001": "利润",
                    "10002": "2147538.9271282256",
                    "10003": "231021185249687",
                    "20001": "利润",
                    "231021185249687": "2147538.9271282256"
                },
                {
                    "10001": "折扣",
                    "10002": "1059.7000162974",
                    "10003": "231021185249690",
                    "20001": "折扣",
                    "231021185249690": "1059.7000162974"
                },
                {
                    "10001": "LOD字段",
                    "10002": "16068954.132933617",
                    "10003": "231021185249693",
                    "20001": "LOD字段",
                    "231021185249693": "16068954.132933617"
                }
            ],
            "fields": {
                "10001": {
                    "alias": "指标名称 "
                },
                "10002": {
                    "alias": "指标值 "
                },
                "20001": {
                    "alias": "图例项 ",
                    "domain": [
                        "数_量",
                        "利润",
                        "折扣",
                        "LOD字段"
                    ],
                    "sortIndex": 0
                },
                "231021185249544": {
                    "alias": "数_量"
                },
                "231021185249687": {
                    "alias": "利润"
                },
                "231021185249690": {
                    "alias": "折扣"
                },
                "231021185249693": {
                    "alias": "LOD字段"
                }
            }
        }
    ],
    "outerRadius": 0.8,
    "label": {
        "visible": true,
        "overlap": {
            "hideOnHit": true,
            "avoidBaseMark": false,
            "strategy": [
                {
                    "type": "moveY",
                    "offset": [
                        -20,
                        -19,
                        -18,
                        -17,
                        -16,
                        -15,
                        -14,
                        -13,
                        -12,
                        -11,
                        -10,
                        -9,
                        -8,
                        -7,
                        -6,
                        -5,
                        -4,
                        -3,
                        -2,
                        -1,
                        0,
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20
                    ]
                },
                {
                    "type": "moveX",
                    "offset": [
                        -20,
                        -19,
                        -18,
                        -17,
                        -16,
                        -15,
                        -14,
                        -13,
                        -12,
                        -11,
                        -10,
                        -9,
                        -8,
                        -7,
                        -6,
                        -5,
                        -4,
                        -3,
                        -2,
                        -1,
                        0,
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20
                    ]
                }
            ]
        },
        "style": {
            "fontSize": 12,
            "zIndex": 400,
            "fill": null,
            "lineWidth": 0,
            "strokeOpacity": 1,
            "angle": 0
        },
        "layout": {
            "tangentConstraint": false
        },
        "position": "outside",
        "smartInvert": false,
        "interactive": false
    },
    "color": {
        "field": "20001",
        "type": "ordinal",
        "range": [
            "#2E62F1",
            "#4DC36A",
            "#FF8406",
            "#FFCC00"
        ],
        "specified": {},
        "domain": [
            "数_量",
            "利润",
            "折扣",
            "LOD字段"
        ]
    },
    "legends": [
        {
            "type": "discrete",
            "id": "legend-discrete",
            "orient": "right",
            "position": "start",
            "layoutType": "normal",
            "visible": true,
            "maxCol": 1,
            "title": {
                "textStyle": {
                    "fontSize": 12,
                    "fill": "#6F6F6F"
                }
            },
            "layoutLevel": 60,
            "item": {
                "focus": true,
                "focusIconStyle": {
                    "size": 14
                },
                "maxWidth": 326,
                "spaceRow": 0,
                "spaceCol": 0,
                "padding": {
                    "top": 1,
                    "bottom": 2,
                    "left": 3,
                    "right": 2
                },
                "background": {
                    "visible": false,
                    "style": {
                        "fillOpacity": 0.001
                    }
                },
                "label": {
                    "style": {
                        "fontSize": 12,
                        "fill": "#6F6F6F"
                    }
                },
                "shape": {
                    "style": {
                        "lineWidth": 0,
                        "symbolType": "square"
                    }
                }
            },
            "pager": {
                "layout": "horizontal",
                "padding": {
                    "left": -18
                },
                "textStyle": {},
                "space": 0,
                "handler": {
                    "preShape": "triangleLeft",
                    "nextShape": "triangleRight",
                    "style": {},
                    "state": {
                        "disable": {}
                    }
                }
            },
            "padding": {
                "top": 0,
                "bottom": 0,
                "left": 16,
                "right": 0
            }
        }
    ],
    "hover": {
        "enable": true
    },
    "select": {
        "enable": true
    },
    "rose": {
        "state": {
            "hover": {
                "cursor": "pointer",
                "fillOpacity": 0.8,
                "stroke": "#58595B",
                "lineWidth": 1,
                "zIndex": 500
            },
            "selected": {
                "cursor": "pointer",
                "fillOpacity": 1,
                "stroke": "#58595B",
                "lineWidth": 1
            },
            "selected_reverse": {
                "fillOpacity": 0.3,
                "strokeWidth": 0.3
            }
        }
    },
    "tooltip": {
        "handler": {}
    },
    "pie": {},
    "region": [
        {
            "clip": true
        }
    ],
    "background": "rgba(255, 255, 255, 0)",
    "animation": false,
    "hash": "d382aff7684524d796a331462cbfadc4"
}
```

### PR DESCRIPTION
**Pull request by zamhown**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #1263 

### 🐞 Bugserver case id
6538de7b6c8f41ad98d786b0

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/axis/base-axis.ts [hunk 1]
```diff
@@ -467,6 +466,10 @@ export abstract class AxisComponent<T extends ICommonAxisSpec & Record<string, a
   addTransformToTickData(options: ITransformOptions, execute?: boolean) {
     this._tickData?.getDataView()?.transform(options, execute);
   }
+
+  dataToPosition(values: any[]): number {
+    return this._scale.scale(values);
```
Comment (kkxxkk2019) [inline packages/vchart/src/component/axis/base-axis.ts:471]: 这个不太对，对于 scale.scale 方法来说应该只接收单个值的

**Review by kkxxkk2019 — APPROVED** [review]
