### PR TITLE
fix: position error in bar chart

### LINKED ISSUE #3242: [Bug] label position function not working
### Version

1.2.4

### Link to Minimal Reproduction

none

### Steps to Reproduce

img_v3_02er_a7a56bfe-030b-479d-a632-9c9655daeaeg

### Current Behavior

none

### Expected Behavior

none

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by youngwinds**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #3242

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |    x       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/label/util.ts [hunk 1]
```diff
@@ -133,15 +133,24 @@ export function barLabel(labelInfo: ILabelInfo) {
...
-    position = (data: Datum) => {
-      const { data: datum } = data;
+  position = (datum: Datum) => {
+    const { data } = datum;
+
+    const labelPosition =
+      typeof labelSpec.position === 'function'
+        ? (labelSpec.position as (a: Datum) => string)(data)
+        : labelSpec.position ?? 'outside';
+
```
Comment (xile611) [inline packages/vchart/src/component/label/util.ts:143]: const labelPosition =
      (typeof labelSpec.position === 'function'
        ? (labelSpec.position as (a: Datum) => string)(data)
        : labelSpec.position) ?? 'outside';

**Review by xile611 — APPROVED** [review]
