### PR TITLE
fix: indicator component does not cleared when chart is updated #250

### LINKED ISSUE #250: [Bug] Indicator component does not cleared when chart is updated
### Version

1.0.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

```ts
const data = [
  { type: 'oxygen', value: '46.60', formula: 'O', texture: 'circle' },
  { type: 'silicon', value: '27.72', formula: 'Si', texture: 'horizontal-line' },
  { type: 'aluminum', value: '8.13', formula: 'Al', texture: 'vertical-line' },
  { type: 'iron', value: '5', formula: 'Fe', texture: 'rect' },
  { type: 'calcium', value: '3.63', formula: 'Ca', texture: 'grid' },
  { type: 'sodium', value: '2.83', formula: 'Na', texture: 'bias-rl' },
  { type: 'potassium', value: '2.59', formula: 'K', texture: 'diamond' },
  { type: 'others', value: '3.5', formula: 'Others', texture: 'bias-lr' }
];
const spec = {
  type: 'pie',
  data: [
    {
      id: 'id0',
      values: data
    }
  ],
  outerRadius: 0.8,
  innerRadius: 0.5,
  padAngle: 0.6,
  valueField: 'value',
  categoryField: 'type',
  pie: {
    style: {
      cornerRadius: 10,
      texture: datum => datum['texture']
    },
    state: {
      hover: {
        outerRadius: 0.85,
        stroke: '#000',
        lineWidth: 1
      },
      selected: {
        outerRadius: 0.85,
        stroke: '#000',
        lineWidth: 1
      }
    }
  },
  title: {
    visible: true,
    text: '地表元素含量统计'
  },
  indicator: {
    visible: true,
    fixed: true,
    title: {
      visible: true,
      autoFit: true,
      style: {
        text: "tex"
      }
    },
    content: [
      {
        visible: true,
        style: {
          fontSize: 20,
          fill: 'orange',
          fontWeight: 'bolder',
          fontFamily: 'Times New Roman',
          text: datum => {
            const d = datum ?? data[0];
            return d['type'];
          }
        }
      },
      {
        visible: true,
        style: {
          fontSize: 18,
          fill: 'orange',
          fontFamily: 'Times New Roman',
          text: datum => {
            const d = datum ?? data[0];
            return d['value'] + '%';
          }
        }
      }
    ]
  },
  legends: {
    visible: true,
    orient: 'left',
    item: {
      shape: {
        style: {
          symbolType: 'circle',
          texture: datum => datum['texture']
        }
      }
    }
  },
  tooltip: {
    mark: {
      content: [
        {
          key: datum => datum['type'],
          value: datum => datum['value'] + '%'
        }
      ]
    }
  }
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// 只为了方便控制台调试用，不要拷贝
window['vchart'] = vchart;

setTimeout(() => {
  vchart.updateSpec(
    {
      ...spec,
      indicator: {
        visible: true,
        fixed: true,
        title: {
          visible: true,
          autoFit: true,
          style: {
            text: "123"
          }
        },
        content: [
          {
            visible: true,
            style: {
              fontSize: 20,
              fill: 'orange',
              fontWeight: 'bolder',
              fontFamily: 'Times New Roman',
              text: "Hello"
            }
          },
          {
            visible: true,
            style: {
              fontSize: 18,
              fill: 'orange',
              fontFamily: 'Times New Roman',
              text: datum => {
                const d = datum ?? data[0];
                return d['value'] + '%';
              }
            }
          }
        ]
      }
    })
}, 1500)
```

### Current Behavior

image

### Expected Behavior

clear

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by pairone**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #250 

### 🐞 Bugserver case id

64c0cefdf92ddeed34228eaa

### 💡 Background and solution

https://github.com/VisActor/VChart/assets/40026218/5ffb8467-024f-4b21-bb17-fd5827226148

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/indicator/indicator.ts [hunk 1]
```diff
@@ -237,8 +237,10 @@ export class Indicator extends BaseComponent implements IIndicator {
   }
 
   clear(): void {
+    if (this._indicatorComponent) {
+      this._container.removeChild(this._indicatorComponent as unknown as INode);
+      this._indicatorComponent = null;
+    }
     super.clear();
-    this._indicatorComponent = null;
-    this._cacheAttrs = null;
```
Comment (kkxxkk2019) [inline packages/vchart/src/component/indicator/indicator.ts:242]: 这个也最好重置下

**Review by kkxxkk2019 — APPROVED** [review]

**Review by xuefei1313 — APPROVED** [review]
