### PR TITLE
fix: fix issue with taro tt env, closed #2648

### LINKED ISSUE #2648: [bug] taro tt and wx env fix

### PR DESCRIPTION
**Pull request by neuqzxy**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/taro-vchart/src/components/general-chart/index.tsx [hunk 1]
```diff
@@ -110,10 +110,17 @@ export class GeneralChart extends React.Component<GeneralChartProps> {
...
+          domref,
+          force: true,
+          canvasIdLists,
+          freeCanvasIdx: 2,
+          component: undefined
+        });
       }
     }
 
+    console.log('dpr', dpr);
```
Comment (xile611) [inline packages/taro-vchart/src/components/general-chart/index.tsx:123]: console.log 需要去掉

**Review by xile611 — APPROVED** [review]
