### PR TITLE
fix: indicator stop tooltip interactive. fix#3123

### LINKED ISSUE #3123: [Bug] indicator stop tooltip interactivation
### Version

1.11.11

### Link to Minimal Reproduction

vscreen

### Steps to Reproduce

```ts
/** --在业务中使用时请添加以下代码-- */
// 在业务中使用时, 请额外引入registerLiquidChart并执行
// import { registerLiquidChart } from '@visactor/vchart';
// registerLiquidChart();
/** --在业务中使用时请添加以上代码-- */

/** --在业务中使用时请删除以下代码-- */
VCHART_MODULE.registerLiquidChart();
/** --在业务中使用时请删除以上代码-- */
const spec = {
  type: 'liquid',
  valueField: 'value',
  data: {
    id: 'data',
    values: [
      {
        value: 0.8
      }
    ]
  },
  indicator: {
    visible: true,
    title: {
      visible: true,
      style: {
        text: '进度'
      }
    },
    content: [
      {
        visible: true,
        style: {
          fill: 'black',
          text: '30%'
        }
      }
    ]
  }
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

### Current Behavior

hover到indicator时，tooltip不触发，设置pickable或interactive属性都不生效

### Expected Behavior

hover到indicator时，tooltip触发

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by skie1997**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #3123 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/indicator/indicator.ts [hunk 1]
```diff
@@ -200,30 +201,32 @@ export class Indicator<T extends IIndicatorSpec> extends BaseComponent<T> implem
     });
 
     return {
-      visible: this._spec.visible !== false && (this._spec.fixed !== false || this._activeDatum !== null),
+      visible: visible !== false && (fixed !== false || this._activeDatum !== null),
```
Comment (xile611) [inline packages/vchart/src/component/indicator/indicator.ts:204]: 这里有一个优化，如果visible最终结果为fasle，下面的属性都没必要解析了

File: packages/vchart/src/component/indicator/indicator.ts [hunk 2]
```diff
@@ -200,30 +201,32 @@ export class Indicator<T extends IIndicatorSpec> extends BaseComponent<T> implem
...
-          ...transformIndicatorStyle(pickWithout(this._spec.title.style, ['text']), this._activeDatum),
-          text: this._createText(this._spec.title.field, this._spec.title.style.text as any) // FIXME: type
+          ...transformIndicatorStyle(pickWithout(title.style, ['text']), this._activeDatum),
+          text: this._createText(title.field, title.style.text as any) // FIXME: type
         }
       },
-      content: contentComponentSpec
+      content: contentComponentSpec,
+      ...(restSpec as unknown as IndicatorAttributes),
+      pickable: false
```
Comment (xile611) [inline packages/vchart/src/component/indicator/indicator.ts:229]: 可能会存在想要手动覆盖pickable 的需求
这里改变了默认行为，最好是pickable 能够读取配置，否则走到默认的逻辑

**Review by xile611 — APPROVED** [review]
