### PR TITLE
Fix/auto bandsize

### LINKED ISSUE #2704: [Bug] autoBandSize not work
### Version

1.11.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

```ts
  const spec = {
    type: "common",
    padding: {
      left: 0,
      right: 0,
      bottom: 0,
      top: 0
    },
    legends: [
      {
        type: "discrete",
        visible: true,
        orient: "bottom",
        maxRow: 1,
        item: {
          label: {}
        }
      }
    ],
    data: [
      {
        id: "seriesData",
        values: [
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[87.00,130.50)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.85,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.02849741,
                tagValidProportion: 0.10091743,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[87.00,130.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 87,
                  max: 130.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 43,
            count: 43,
            tagShowValue: "[43.50,87.00)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.78,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.027849741,
                tagValidProportion: 0.09862386,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 43,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[43.50,87.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 43.5,
                  max: 87,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[391.50,435.00]",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.85,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.02849741,
                tagValidProportion: 0.10091743,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[391.50,435.00]",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 391.5,
                  max: 435,
                  leftClose: true,
                  rightClose: true
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[348.00,391.50)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.85,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.02849741,
                tagValidProportion: 0.10091743,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[348.00,391.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 348,
                  max: 391.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 43,
            count: 43,
            tagShowValue: "[304.50,348.00)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.78,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.027849741,
                tagValidProportion: 0.09862386,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 43,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[304.50,348.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 304.5,
                  max: 348,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[261.00,304.50)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.85,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.02849741,
                tagValidProportion: 0.10091743,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[261.00,304.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 261,
                  max: 304.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 43,
            count: 43,
            tagShowValue: "[217.50,261.00)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.78,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.027849741,
                tagValidProportion: 0.09862386,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 43,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[217.50,261.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 217.5,
                  max: 261,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[174.00,217.50)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.85,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.02849741,
                tagValidProportion: 0.10091743,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[174.00,217.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 174,
                  max: 217.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 43,
            count: 43,
            tagShowValue: "[130.50,174.00)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.78,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.027849741,
                tagValidProportion: 0.09862386,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 43,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[130.50,174.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 130.5,
                  max: 174,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[0.00,43.50)",
            segName: "ccc",
            segIndex: 3,
            tgi: 778,
            tgiName: "778",
            percentage: 2.85,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.02849741,
                tagValidProportion: 0.10091743,
                tagTGI: 100,
                mauTGI: 778,
                customTGI: 778,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[0.00,43.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 0,
                  max: 43.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "ccc",
              segIndex: 3
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[87.00,130.50)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.75,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.0075290897,
                tagValidProportion: 0.101149425,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[87.00,130.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 87,
                  max: 130.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 43,
            count: 43,
            tagShowValue: "[43.50,87.00)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.74,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.007357974,
                tagValidProportion: 0.09885058,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 43,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[43.50,87.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 43.5,
                  max: 87,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[391.50,435.00]",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.75,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.0075290897,
                tagValidProportion: 0.101149425,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[391.50,435.00]",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 391.5,
                  max: 435,
                  leftClose: true,
                  rightClose: true
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[348.00,391.50)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.75,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.0075290897,
                tagValidProportion: 0.101149425,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[348.00,391.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 348,
                  max: 391.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 43,
            count: 43,
            tagShowValue: "[304.50,348.00)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.74,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.007357974,
                tagValidProportion: 0.09885058,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 43,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[304.50,348.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 304.5,
                  max: 348,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[261.00,304.50)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.75,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.0075290897,
                tagValidProportion: 0.101149425,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[261.00,304.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 261,
                  max: 304.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 43,
            count: 43,
            tagShowValue: "[217.50,261.00)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.74,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.007357974,
                tagValidProportion: 0.09885058,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 43,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[217.50,261.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 217.5,
                  max: 261,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 44,
            count: 44,
            tagShowValue: "[174.00,217.50)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.75,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.0075290897,
                tagValidProportion: 0.101149425,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 44,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[174.00,217.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 174,
                  max: 217.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 43,
            count: 43,
            tagShowValue: "[130.50,174.00)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 205,
            tgiName: "205",
            percentage: 0.74,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.007357974,
                tagValidProportion: 0.09885058,
                tagTGI: 100,
                mauTGI: 205,
                customTGI: 205,
                countInSeg: 43,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[130.50,174.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 130.5,
                  max: 174,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 44,
            count: 43,
            tagShowValue: "[0.00,43.50)",
            segName: "fasfdsafdsa",
            segIndex: 2,
            tgi: 201,
            tgiName: "201",
            percentage: 0.74,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0.007357974,
                tagValidProportion: 0.09885058,
                tagTGI: 97,
                mauTGI: 201,
                customTGI: 201,
                countInSeg: 43,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[0.00,43.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 0,
                  max: 43.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "fasfdsafdsa",
              segIndex: 2
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[87.00,130.50)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0.25,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[87.00,130.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 87,
                  max: 130.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 43,
            count: 0,
            tagShowValue: "[43.50,87.00)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0.33,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[43.50,87.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 43.5,
                  max: 87,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[391.50,435.00]",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[391.50,435.00]",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 391.5,
                  max: 435,
                  leftClose: true,
                  rightClose: true
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[348.00,391.50)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[348.00,391.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 348,
                  max: 391.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 43,
            count: 0,
            tagShowValue: "[304.50,348.00)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[304.50,348.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 304.5,
                  max: 348,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[261.00,304.50)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[261.00,304.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 261,
                  max: 304.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 43,
            count: 0,
            tagShowValue: "[217.50,261.00)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[217.50,261.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 217.5,
                  max: 261,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[174.00,217.50)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[174.00,217.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 174,
                  max: 217.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 43,
            count: 0,
            tagShowValue: "[130.50,174.00)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0.99,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[130.50,174.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 130.5,
                  max: 174,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[0.00,43.50)",
            segName: "分群2",
            segIndex: 1,
            tgi: 0,
            tgiName: "0",
            percentage: 0.23,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[0.00,43.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 0,
                  max: 43.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群2",
              segIndex: 1
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[87.00,130.50)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0.87,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[87.00,130.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 87,
                  max: 130.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 43,
            count: 0,
            tagShowValue: "[43.50,87.00)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0.27,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[43.50,87.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 43.5,
                  max: 87,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[391.50,435.00]",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[391.50,435.00]",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 391.5,
                  max: 435,
                  leftClose: true,
                  rightClose: true
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[348.00,391.50)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[348.00,391.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 348,
                  max: 391.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 43,
            count: 0,
            tagShowValue: "[304.50,348.00)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[304.50,348.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 304.5,
                  max: 348,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[261.00,304.50)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[261.00,304.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 261,
                  max: 304.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 43,
            count: 0,
            tagShowValue: "[217.50,261.00)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[217.50,261.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 217.5,
                  max: 261,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[174.00,217.50)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[174.00,217.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 174,
                  max: 217.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 43,
            count: 0,
            tagShowValue: "[130.50,174.00)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0.1,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 43,
                countInCustomTGISeg: 43,
                tagShowValue: "[130.50,174.00)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 130.5,
                  max: 174,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          },
          {
            countInMau: 44,
            count: 0,
            tagShowValue: "[0.00,43.50)",
            segName: "分群1",
            segIndex: 0,
            tgi: 0,
            tgiName: "0",
            percentage: 0.77,
            placeholder: 0,
            originData: {
              data: {
                tagProportion: 0,
                tagValidProportion: "NaN",
                tagTGI: 0,
                mauTGI: 0,
                customTGI: 0,
                countInSeg: 0,
                countInMau: 44,
                countInCustomTGISeg: 44,
                tagShowValue: "[0.00,43.50)",
                tagDateRange: null,
                tagDateTimeRange: null,
                tagDecimalRange: {
                  min: 0,
                  max: 43.5,
                  leftClose: true,
                  rightClose: false
                },
                tagDecimalValue: null,
                tagStringValue: null,
                tagDateValue: null,
                tagDateTimeValue: null
              },
              segName: "分群1",
              segIndex: 0
            }
          }
        ]
      }
    ],
    series: [
      {
        type: "bar",
        id: "barSeries",
        dataId: "seriesData",
        direction: "horizontal",
        yField: ["tagShowValue", "segName"],
        xField: "percentage",
        seriesField: "segName",
        stack: false,
        // barWidth: 10,
        // barGapInGroup: 0.2,
        // autoBandSize: true,
        bar: {
          style: {
            lineWidth: 0
          }
        }
      },
      {
        type: "bar",
        id: "tgiBarSeries",
        dataId: "seriesData",
        direction: "horizontal",
        yField: ["tagShowValue", "segName"],
        xField: "tgi",
        // barWidth: 10,
        // barGapInGroup: 0.2,
        // autoBandSize: true,
        bar: {
          style: {
            fill: {
              field: "segName",
              scale: "tgiColorScale"
            }
          }
        }
      }
    ],
    axes: [
      {
        orient: "bottom",
        id: "leftId",
        type: "linear",
        seriesId: ["barSeries"],
        label: {
          padding: 6
        },
        gridDash: [0, 0],
        title: {
          visible: false
        },
        unit: {
          visible: true,
          margin: {
            left: -20
          }
        }
      },
      {
        visible: true,
        orient: "top",
        type: "linear",
        sync: {
          axisId: "leftId",
          tickAlign: true
        },
        seriesId: ["tgiBarSeries"],
        label: {
          padding: 6
        },
        gridDash: [0, 0],
        zero: true,
        bandSize: 50
      },
      {
        orient: "left",
        type: "band",
        groupSize: 80,
        bandSize: 50
      }
    ],
    markLine: [
      {
        x: 100,
        relativeSeriesId: "tgiBarSeries",
        label: {
          visible: true,
          confine: true,
          text: "TGI 100",
          style: {
            fontSize: 12,
            fontWeight: "bold",
            fill: "red",
            dx: 10,
            suffixPosition: "end"
          },
          labelBackground: {
            visible: false
          }
        },
        startSymbol: {
          visible: false
        },
        endSymbol: {
          visible: false
        },
        line: {
          label: {
            visible: true,
            text: "TGI 100"
          },
          style: {
            stroke: "red",
            lineDash: [4]
          }
        }
      }
    ],
    scales: [
      {
        id: "colorScale",
        type: "ordinal",
        domain: [
          {
            dataId: "seriesData",
            fields: ["segName"]
          }
        ],
        range: [
          "#1664FF",
          "#3CC780",
          "#FF8A00",
          "#1AC6FF",
          "#7442D4",
          "#FFC400",
          "#B48DEB",
          "#009488",
          "#304D77",
          "#FF7DDA"
        ]
      },
      {
        id: "tgiColorScale",
        type: "ordinal",
        domain: [
          {
            dataId: "seriesData",
            fields: ["segName"]
          }
        ],
        range: [
          "#B2CFFF",
          "#B9EDCD",
          "#FFCE7A",
          "#94EFFF",
          "#DDC5FA",
          "#FAE878",
          "#EFE3FF",
          "#59BAA8",
          "#8B959E",
          "#FFCFEE"
        ]
      }
    ],
    scrollBar: [
      {
        orient: "right",
        auto: true
      }
    ]
  };
```

### Current Behavior

设置barWidth和autoBandSize之后，柱子没有自动调整bandSize导致柱子重叠
img_v3_02av_daeb7888-55db-41ba-930f-2a5745799e5g

### Expected Behavior

autoBandSize生效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by skie1997**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #2704 

### 🐞 Bugserver case id
665323210b3b8900c63a78b0

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/chart/common/common-transformer.ts [hunk 1]
```diff
@@ -15,6 +16,68 @@ export class CommonChartSpecTransformer<T extends ICommonChartSpec = ICommonChar
...
+  protected _transformAxisSpec(spec: AdaptiveSpec<T, 'series'>) {
+    if (!spec.axes) {
+      return;
+    }
+    // 遍历series
+    // 1. 找到bar系列
+    // 2. 如果bar系列配置了autoBandSize
+    // 3. 找到bar系列对应的axis
+    // 4. 为该axis配置bandSize
+    spec.series.forEach((series: any, seriesIndex: number) => {
```
Comment (xile611) [inline packages/vchart/src/chart/common/common-transformer.ts:29]: 柱图中的类似逻辑需要统一一下

File: packages/vchart-types/types/series/bar/interface.d.ts [hunk 2]
```diff
@@ -23,6 +23,9 @@ export interface IBarSeriesSpec extends ICartesianSeriesSpec, IAnimationSpec<Bar
     barGapInGroup?: number | string | (number | string)[];
     barMinHeight?: number;
     stackCornerRadius?: number | number[];
+    autoBandSize?: boolean | {
```
Comment (xile611) [inline packages/vchart-types/types/series/bar/interface.d.ts:26]: 这个应该是图表配置吧，而不是系列配置

File: packages/vchart/src/series/bar/interface.ts [hunk 3]
```diff
@@ -101,6 +101,16 @@ export interface IBarSeriesSpec
    * @since 1.10.0
    */
   stackCornerRadius?: number | number[];
+  /**
+   * 是否开启自动 bandSize。如果开启，会根据传入的 barWidth 等配置自动计算 bandSize，从而影响轴实际长度
+   * @since 1.11.2
+   */
+  autoBandSize?:
```
Comment (xile611) [inline packages/vchart/src/series/bar/interface.ts:108]: 这个应该是图表配置吧，而不是系列配置

File: packages/vchart-types/types/series/bar/interface.d.ts (hunk 2 above)
Comment (skie1997) [reply packages/vchart-types/types/series/bar/interface.d.ts:26]: 业务方期望在common chart中也能配置这个属性，所以在这里做了兼容处理，支持在系列上也配置

Comment (xile611) [reply packages/vchart-types/types/series/bar/interface.d.ts:26]: > 业务方期望在common chart中也能配置这个属性，所以在这里做了兼容处理，支持在系列上也配置

可以在common chart中支持，但是这个应该是图表配置才对

**Review by xile611 — APPROVED** [review]
