### PR TITLE
Fix/parent element

### LINKED ISSUE #641: [Bug] Error when configuring `tooltip.parentElement` with a HTMLElement object

### PR DESCRIPTION
**Pull request by zamhown**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #641 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/util/spec.ts [hunk 1]
```diff
@@ -97,6 +97,10 @@ export function isDataView(obj: any): obj is DataView {
   return obj instanceof DataView || dataViewKeys.every(key => keys.includes(key));
 }
 
+export function isHTMLElement(obj: any): obj is Element {
+  return obj instanceof Element;
```
Comment (kkxxkk2019) [inline packages/vchart/src/util/spec.ts:101]: 这个跨端环境会不会有问题

Comment (zamhown) [reply packages/vchart/src/util/spec.ts:101]: 小程序是没有Element这个对象声明吗，我看下改成判断几个特征key值试试

**Review by kkxxkk2019 — APPROVED** [review]
