### PR TITLE
Fix/stack default

### LINKED ISSUE #557: [Bug]bar didnt' stack as expected with spec configured `percent: false` and without configure `stack`
### Version

1.2.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

`percent: false` and without configure `stack`

### Current Behavior

did not stack

### Expected Behavior

stack default in bar chart

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xiaoluoHe**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #557 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/series/base/base-series.ts [hunk 1]
```diff
@@ -289,11 +289,11 @@ export abstract class BaseSeries<T extends ISeriesSpec> extends BaseModel implem
     }
     if (isBoolean(this._spec.percent)) {
       this._percent = this._spec.percent;
-      this._stack = this._spec.stack || this._spec.percent;
+      this._stack = this._spec.stack || this._spec.percent || this._stack; // this._stack is `true` in bar/area series
```
Comment (xuefei1313) [inline packages/vchart/src/series/base/base-series.ts:292]: this._stack 在这里已经包含了 this._spec.stack 了吧。可以去掉?

**Review by xuefei1313 — APPROVED** [review]
