### PR TITLE
Fix/pie chart with null value

### LINKED ISSUE #748: [Bug] pie chart render empty when value is null
Image

```ts
const spec = {
  "type": "pie",
  "categoryField": "20001",
  "valueField": "230901153400086",
  "seriesField": "20001",
  "padding": 0,
  "data": [
    {
      "id": "data",
      "values": [
        {
          "20001": "华东",
          "230901144537180": "华东",
          "230901153400086": "4684506.442247391"
        },
        {
          "20001": "中南",
          "230901144537180": "中南",
          "230901153400086": "4137415.0951108932"
        },
        {
          "20001": "地区-dongbei",
          "230901144537180": "地区-dongbei",
          "230901153400086": "2681567.4745378494"
        },
        {
          "20001": "西南",
          "230901144537180": "西南",
          "230901153400086": "1303124.5089645386"
        },
        {
          "20001": "西北",
          "230901144537180": "西北",
          "230901153400086": "815039.5979347229"
        },
        {
          "20001": "华北",
          "230901144537180": "华北",
          "230901153400086": null
        }
      ],
      "fields": {
        "20001": {
          "alias": "图例项 ",
          "domain": [
            "华东",
            "中南",
            "地区-dongbei",
            "西南",
            "西北",
            "华北"
          ],
          "lockStatisticsByDomain": true
        },
        "230901144537180": {
          "alias": "地区"
        },
        "230901153400086": {
          "alias": "销售额-存在空"
        }
      }
    }
  ],
  "outerRadius": 0.9,
  "label": {
    "visible": true,
    "overlap": {
      "hideOnHit": true
    },
    "style": {
      "fontSize": 12,
      "fill": null,
      "lineWidth": 0,
      "strokeOpacity": 1
    },
    "position": "outside",
    "interactive": false
  },
  "color": {
    "field": "20001",
    "type": "ordinal",
    "range": [
      "#2E62F1",
      "#4DC36A",
      "#FF8406",
      "#FFCC00",
      "#4F44CF",
      "#5AC8FA"
    ],
    "specified": {},
    "domain": [
      "华东",
      "中南",
      "地区-dongbei",
      "西南",
      "西北",
      "华北"
    ]
  },
  "legends": [
    {
      "type": "discrete",
      "id": "legend",
      "orient": "right",
      "position": "start",
      "layoutType": "normal",
      "visible": true,
      "maxCol": 1,
      "title": {
        "textStyle": {
          "fontSize": 12,
          "fill": "#6F6F6F"
        }
      },
      "item": {
        "focus": true,
        "focusIconStyle": {
          "size": 14
        },
        "maxWidth": 325,
        "spaceRow": 0,
        "spaceCol": 0,
        "padding": {
          "top": 1,
          "bottom": 1,
          "left": 2,
          "right": 2
        },
        "background": {
          "visible": false,
          "style": {
            "fillOpacity": 0.001
          }
        },
        "label": {
          "style": {
            "fontSize": 12,
            "fill": "#6F6F6F"
          }
        },
        "shape": {
          "style": {
            "lineWidth": 0,
            "symbolType": "square"
          }
        }
      },
      "pager": {
        "textStyle": {},
        "handler": {
          "style": {},
          "state": {
            "disable": {}
          }
        }
      },
      "padding": {
        "top": 0,
        "bottom": 0,
        "left": 16,
        "right": 0
      }
    }
  ],
  "hover": {
    "enable": true
  },
  "select": {
    "enable": true
  },
  "pie": {
    "state": {
      "hover": {
        "cursor": "pointer",
        "fillOpacity": 0.8,
        "stroke": "#58595B",
        "lineWidth": 1,
        "zIndex": 500,
        "outerRadius": 0.9500000000000001
      },
      "selected": {
        "cursor": "pointer",
        "fillOpacity": 1,
        "stroke": "#58595B",
        "lineWidth": 1,
        "outerRadius": 0.9500000000000001
      },
      "selected_reverse": {
        "fillOpacity": 0.3,
        "strokeWidth": 0.3
      }
    }
  },
  "tooltip": {
    "handler": {}
  },
  "background": "rgba(255, 255, 255, 0)",
  "rose": {},
  "animation": false,
  "hash": "8fefead4c53c18c47279796bce64468e"
}

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderAsync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;

```

### PR DESCRIPTION
**Pull request by kkxxkk2019**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #748 

### 🐞 Bugserver case id

64f1f6682a78e9f552b7422d

| before | after |
|--------|--------|
|image | image |

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

**Review by xuefei1313 — APPROVED** [review]

File: packages/vchart/src/data/transforms/pie.ts [hunk 1]
```diff
@@ -35,13 +42,13 @@ export const pie = (originData: Array<DataView>, op: IPieOpt) => {
     asK
   } = op;
 
-  const total = data.reduce((sum, d) => Number.parseFloat(d[angleField]) + sum, 0);
-  const max = data.reduce((m, d) => Math.max(m, Number.parseFloat(d[angleField])), -Infinity);
+  const total = data.reduce((sum, d) => transformInvalidValue(d[angleField]) + sum, 0);
+  const max = data.reduce((m, d) => Math.max(m, transformInvalidValue(d[angleField])), -Infinity);
```
Comment (xuefei1313) [inline packages/vchart/src/data/transforms/pie.ts:46]: 可以尝试合并到一次reduce里？transformInvalidValue可以减少一次

**Review by xuefei1313 — APPROVED** [review]

**Review by xuefei1313 — APPROVED** [review]
