### PR TITLE
Fix/tooltip text measure

### LINKED ISSUE #1346: [Bug] 飞书小程序，当数值为 0 时 tooltip上不能展示
### Version

latest

### Link to Minimal Reproduction

none

### Steps to Reproduce

spec:

```ts
const spec = {
            type: 'bar',
            data: [
                {
                    id: 'barData',
                    values: [
                        { type: "建联品牌数", x: "CKA", y: 0 },
                        { type: "有效品牌数", x: "CKA", y: 0 },
                        { type: "建联品牌数", x: "连锁", y: 0 },
                        { type: "有效品牌数", x: "连锁", y: 0 },
                        { type: "建联品牌数", x: "TKA", y: 0 },
                        { type: "有效品牌数", x: "TKA", y: 0 }, 
                        { type: "建联品牌数", x: "华北大区", y: 0 },
                        { type: "有效品牌数", x: "华北大区", y: 0 },
                        { type: "建联品牌数", x: "华中大区", y: 0 },
                        { type: "有效品牌数", x: "华中大区", y: 0 },
                        { type: "建联品牌数", x: "华东大区", y: 2 },
                        { type: "有效品牌数", x: "华东大区", y: 0 },
                        { type: "建联品牌数", x: "西南大区", y: 0 },
                        { type: "有效品牌数", x: "西南大区", y: 0 },
                        { type: "建联品牌数", x: "华南大区", y: 0 },
                        { type: "有效品牌数", x: "华南大区", y: 0 }
                    ]
                }
            ],
            direction: 'horizontal',
            xField: 'y',
            yField: ['x', 'type'],
            seriesField: 'type',
            legends: {
                visible: true,
                orient: 'bottom'
            },

            axes: [
                {
                    min: 1,
                    orient: 'left',
                    paddingInner: 0,
                }
            ],
        };
```

### Current Behavior

image

### Expected Behavior

展示全

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by zamhown**
[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #1346 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/component/tooltip/handler/utils/common.ts [hunk 1]
```diff
@@ -136,46 +136,30 @@ interface ITooltipTextInfo {
...
-    });
-    return {
-      width: bound.width(),
-      height: bound.height(),
-      text: textLines
-    };
+  let textLines: string[];
+  if (style.multiLine) {
+    textLines = text.split('\n');
+    textLines.map((line, i) => (i < textLines.length - 1 ? line + '\n' : line));
```
Comment (kkxxkk2019) [inline packages/vchart/src/component/tooltip/handler/utils/common.ts:142]: 这个是不是忘记赋值了

**Review by kkxxkk2019 — APPROVED** [review]
