### PR TITLE
fix: fix the issue where map drag interaction cannot be terminated ou…

### LINKED ISSUE #3650: [Bug] 地图拖拽事件不符合预期
### Version

1.13.3

### Link to Minimal Reproduction

null

### Steps to Reproduce

https://visactor.bytedance.net/vchart/demo/map-chart/scatter-map

```ts
const response = await fetch('https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/geojson/world.json');
const geojson = await response.json();
VChart.registerMap('world', geojson);

const dataResponse = await fetch('https://lf9-dp-fe-cms-tos.byteorg.com/obj/bit-cloud/geojson/earthquake.json');
const earthquakeData = await dataResponse.json();

const spec = {
  type: 'common',
  region: [
    {
      roam: true,
      coordinate: 'geo',
      longitudeField: 'lng',
      latitudeField: 'lat',
      projection: {
        type: 'equirectangular'
      }
    }
  ],
  title: {
    text: '全球地震数据等级可视化'
  },
  background: 'rgb(240, 248, 255)',
  data: [{ values: earthquakeData.values }],
  series: [
    { type: 'map', map: 'world', tooltip: { visible: false }, defaultFillColor: 'rgb(245,255,250)' },
    {
      type: 'scatter',
      xField: 'time',
      yField: 'level',
      point: {
        style: {
          size: datum => {
            return datum.level > 7 ? +datum.level * 2 : +datum.level;
          },
          fill: 'red',
          fillOpacity: 0.2
        }
      }
    }
  ]
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```

### Current Behavior

拖拽画布，并在移出画布后抬起鼠标，再次移入画布，事件依然响应
20250108142524_rec_

### Expected Behavior

拖拽画布，并在移出画布后抬起鼠标，再次移入画布，事件不响应

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by xiaoluoHe**
…tside the canvas

[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
closes #3650

### 🐞 Bugserver case id
fileid=677f863944ae5e00b2b66221&interactionid=677f86573a88ae00b2d84d55

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vchart/src/interaction/zoom/zoomable.ts [hunk 1]
```diff
@@ -473,7 +473,10 @@ export class Zoomable implements IZoomable {
       } as unknown as BaseEventParams);
       this._zoomableTrigger.pointerId = null;
       this._eventObj.off(move, { level: Event_Bubble_Level.chart, source: Event_Source_Type.chart }, mousemove as any);
-      this._eventObj.off(end, { level: Event_Bubble_Level.chart, source: Event_Source_Type.window }, mouseup as any);
+      [end, `${end}outside`].forEach(type => {
```
Comment (xile611) [inline packages/vchart/src/interaction/zoom/zoomable.ts:476]: @xiaoluoHe 是不是应该修改配置，将end 事件设置成 ['pointerup', 'pointerupoutside'] 更好，这里写的很死

packages/vchart/src/component/common/trigger/config.ts

**Review by xile611 — APPROVED** [review]
