### PR TITLE
fix: tooltip content is out of bounds in some uncommon case, related …

### LINKED ISSUE #397: [Bug] tooltip unexpected line break
Image

偶现。
原因：dom tooltip 需要用 vrender 的富文本能力进行文本测量，有某些偶然情况下，文本在 canvas 上不会换行，但是在 dom 上会换行，因此高度超过了测量值。

### PR DESCRIPTION
**Pull request by zamhown**
…#397

[[中文版模板 / Chinese template](https://github.com/VisActor/VChart/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Release
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close #397

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

**Review by xuefei1313 — DISMISSED** [review]

File: packages/vchart/src/component/tooltip/handler/dom/interface.ts [hunk 1]
```diff
@@ -5,6 +5,7 @@ export interface IDomTooltipStyle {
     IBorder & {
       width?: string;
       height?: string;
+      minHeight?: string;
```
Comment (kkxxkk2019) [inline packages/vchart/src/component/tooltip/handler/dom/interface.ts:8]: 补充 rush changelog。同时把用户的 spec 录入到 bugserver

**Review by kkxxkk2019 — APPROVED** [review]
